"""Explicit rule fixtures; these are not live official presets."""
from copy import deepcopy

_DECKS = {'requiem': {'id': 'requiem',
             'name': '浊燃预组',
             'official': True,
             'character_ids': ['anhunqu', 'canhong', 'zaowu', 'lingke'],
             'card_ids': ['A01',
                          'A01',
                          'A02',
                          'A02',
                          'A03',
                          'A03',
                          'A08',
                          'A08',
                          'C01',
                          'C01',
                          'C02',
                          'C02',
                          'C03',
                          'C03',
                          'C08',
                          'C08',
                          'S01',
                          'S01',
                          'S03',
                          'S03',
                          'S05',
                          'S05',
                          'S07',
                          'S07',
                          'K01',
                          'K01',
                          'K03',
                          'K03',
                          'K05',
                          'K05',
                          'K08',
                          'K08']},
 'sync-curse': {'id': 'sync-curse',
                'name': '覆纹预组（测试）',
                'official': True,
                'character_ids': ['canhong', 'zaowu', 'iloy', 'lingke'],
                'card_ids': ['C01',
                             'C01',
                             'C02',
                             'C02',
                             'C03',
                             'C03',
                             'C08',
                             'C08',
                             'S01',
                             'S01',
                             'S03',
                             'S03',
                             'S05',
                             'S05',
                             'S07',
                             'S07',
                             'K01',
                             'K01',
                             'K03',
                             'K03',
                             'K05',
                             'K05',
                             'K08',
                             'K08',
                             'Y01',
                             'Y01',
                             'Y02',
                             'Y02',
                             'Y03',
                             'Y03',
                             'Y08',
                             'Y08']}}


def test_character_deck(preset_id):
    return deepcopy(_DECKS[preset_id])
