"""Native/CUDA C99 Random primitives matching CPython Random MT19937 integer seeding.

This module provides:
1. Python helper `seed_words(seed: int) -> list[int]`: Converts an integer seed into
   little-endian uint32 words matching CPython's internal `Random.seed(int)` logic
   (abs value, trailing high zero words normalized away, seed=0 -> [0], rejects bool).
2. `emit_random_source() -> str`: Returns self-contained C99 header source code
   containing MT19937 state and random primitives prefixed with `bmt_`.
   The code supports optional CUDA compilation by configuring the macro `BMT_DEVICE`.

Importing this module does not trigger C compilation or CUDA runtime dependencies.
"""

from typing import List

# Error status codes matching C enum bmt_status_t
BMT_OK = 0
BMT_ERR_NULL_POINTER = 1
BMT_ERR_INVALID_ARG = 2
BMT_ERR_INVALID_BITS = 3
BMT_ERR_EMPTY_RANGE = 4


def seed_words(seed: int) -> List[int]:
    """Convert an integer seed into little-endian uint32 words matching CPython Random.seed(int).

    Strictly rejects boolean values. Normalizes away high-order zero words;
    a seed of 0 produces exactly [0].
    """
    if isinstance(seed, bool) or not isinstance(seed, int):
        raise TypeError(f"seed must be an int, not {type(seed).__name__}")
    val = abs(seed)
    if val == 0:
        return [0]
    words: List[int] = []
    while val > 0:
        words.append(val & 0xFFFFFFFF)
        val >>= 32
    return words


def emit_random_source() -> str:
    """Return self-contained C99 header source code for MT19937 random primitives."""
    return """/* Self-contained C99 MT19937 Random primitives matching CPython Random integer seeding.
 * Generated by emit_random_source(). Do not edit directly if embedded.
 */
#ifndef BMT_RANDOM_SOURCE_H
#define BMT_RANDOM_SOURCE_H

#if defined(__CUDACC_RTC__)
typedef unsigned int uint32_t;
typedef unsigned long long uint64_t;
typedef int int32_t;
#ifndef NULL
#define NULL 0
#endif
#else
#include <stdint.h>
#include <stddef.h>
#endif

#ifndef BMT_DEVICE
#define BMT_DEVICE
#endif

/* MT19937 Constants */
#define BMT_MT_N 624
#define BMT_MT_M 397
#define BMT_MATRIX_A 0x9908b0dfU
#define BMT_UPPER_MASK 0x80000000U
#define BMT_LOWER_MASK 0x7fffffffU

/* Status / Error Codes */
typedef enum {
    BMT_OK = 0,
    BMT_ERR_NULL_POINTER = 1,
    BMT_ERR_INVALID_ARG = 2,
    BMT_ERR_INVALID_BITS = 3,
    BMT_ERR_EMPTY_RANGE = 4
} bmt_status_t;

/* MT19937 Generator State */
typedef struct {
    uint32_t mt[BMT_MT_N];
    int index;
} bmt_state_t;

/* Initialize generator with a single 32-bit constant (Knuth TAOCP Vol2) */
BMT_DEVICE static inline void bmt_init_genrand(bmt_state_t *state, uint32_t s) {
    state->mt[0] = s & 0xffffffffU;
    for (state->index = 1; state->index < BMT_MT_N; state->index++) {
        uint32_t prev = state->mt[state->index - 1];
        state->mt[state->index] = (1812433253U * (prev ^ (prev >> 30)) + (uint32_t)state->index) & 0xffffffffU;
    }
}

/* Initialize generator with an array of little-endian uint32 seed words (CPython style) */
BMT_DEVICE static inline void bmt_init_by_array(bmt_state_t *state, const uint32_t *init_key, size_t key_length) {
    size_t i = 1;
    size_t j = 0;
    size_t k = (BMT_MT_N > key_length ? BMT_MT_N : key_length);
    bmt_init_genrand(state, 19650218U);
    for (; k > 0; k--) {
        uint32_t prev = state->mt[i - 1];
        state->mt[i] = ((state->mt[i] ^ ((prev ^ (prev >> 30)) * 1664525U))
                        + init_key[j] + (uint32_t)j) & 0xffffffffU;
        i++;
        j++;
        if (i >= BMT_MT_N) {
            state->mt[0] = state->mt[BMT_MT_N - 1];
            i = 1;
        }
        if (j >= key_length) {
            j = 0;
        }
    }
    for (k = BMT_MT_N - 1; k > 0; k--) {
        uint32_t prev = state->mt[i - 1];
        state->mt[i] = ((state->mt[i] ^ ((prev ^ (prev >> 30)) * 1566083941U))
                        - (uint32_t)i) & 0xffffffffU;
        i++;
        if (i >= BMT_MT_N) {
            state->mt[0] = state->mt[BMT_MT_N - 1];
            i = 1;
        }
    }
    state->mt[0] = 0x80000000U; /* MSB is 1; assuring non-zero initial array */
    state->index = BMT_MT_N;
}

/* Seed state from little-endian uint32 words. Returns error if state/words null or n==0 */
BMT_DEVICE static inline bmt_status_t bmt_seed_words(bmt_state_t *state, const uint32_t *words, size_t n) {
    if (state == NULL || words == NULL) {
        return BMT_ERR_NULL_POINTER;
    }
    if (n == 0) {
        return BMT_ERR_INVALID_ARG;
    }
    bmt_init_by_array(state, words, n);
    return BMT_OK;
}

/* Core 32-bit word generator */
BMT_DEVICE static inline uint32_t bmt_raw_u32(bmt_state_t *state) {
    uint32_t y;
    if (state->index >= BMT_MT_N) {
        int kk;
        for (kk = 0; kk < BMT_MT_N - BMT_MT_M; kk++) {
            y = (state->mt[kk] & BMT_UPPER_MASK) | (state->mt[kk + 1] & BMT_LOWER_MASK);
            state->mt[kk] = state->mt[kk + BMT_MT_M] ^ (y >> 1) ^ ((y & 1U) ? BMT_MATRIX_A : 0U);
        }
        for (; kk < BMT_MT_N - 1; kk++) {
            y = (state->mt[kk] & BMT_UPPER_MASK) | (state->mt[kk + 1] & BMT_LOWER_MASK);
            state->mt[kk] = state->mt[kk + (BMT_MT_M - BMT_MT_N)] ^ (y >> 1) ^ ((y & 1U) ? BMT_MATRIX_A : 0U);
        }
        y = (state->mt[BMT_MT_N - 1] & BMT_UPPER_MASK) | (state->mt[0] & BMT_LOWER_MASK);
        state->mt[BMT_MT_N - 1] = state->mt[BMT_MT_M - 1] ^ (y >> 1) ^ ((y & 1U) ? BMT_MATRIX_A : 0U);
        state->index = 0;
    }

    y = state->mt[state->index++];

    /* Tempering */
    y ^= (y >> 11);
    y ^= (y << 7) & 0x9d2c5680U;
    y ^= (y << 15) & 0xefc60000U;
    y ^= (y >> 18);

    return y;
}

/* Output single uint32 value with error check */
BMT_DEVICE static inline bmt_status_t bmt_u32(bmt_state_t *state, uint32_t *out) {
    if (state == NULL || out == NULL) {
        return BMT_ERR_NULL_POINTER;
    }
    *out = bmt_raw_u32(state);
    return BMT_OK;
}

/* Sample k bits (0 <= k <= 64) matching CPython Random.getrandbits(k).
 * For k <= 32: draws 1 word, returns high k bits (genrand >> (32 - k)).
 * For k > 32: draws little-endian words, shifting excess bits from the highest word.
 */
BMT_DEVICE static inline bmt_status_t bmt_getbits64(bmt_state_t *state, int k, uint64_t *out) {
    if (state == NULL || out == NULL) {
        return BMT_ERR_NULL_POINTER;
    }
    if (k < 0 || k > 64) {
        return BMT_ERR_INVALID_BITS;
    }
    if (k == 0) {
        *out = 0ULL;
        return BMT_OK;
    }
    if (k <= 32) {
        uint32_t w = bmt_raw_u32(state);
        *out = (uint64_t)(w >> (32 - k));
        return BMT_OK;
    }
    {
        uint32_t w0 = bmt_raw_u32(state);
        uint32_t w1 = bmt_raw_u32(state);
        int excess = 64 - k;
        w1 >>= excess;
        *out = ((uint64_t)w1 << 32) | (uint64_t)w0;
        return BMT_OK;
    }
}

/* Compute bit_length matching Python's int.bit_length() for uint64 */
BMT_DEVICE static inline int bmt_bit_length_u64(uint64_t n) {
    if (n == 0) {
        return 0;
    }
#if defined(__CUDA_ARCH__)
    return 64 - __clzll(n);
#elif defined(__GNUC__) || defined(__clang__)
    return 64 - __builtin_clzll(n);
#else
    int len = 0;
    while (n != 0) {
        len++;
        n >>= 1;
    }
    return len;
#endif
}

/* Sample random uint64 in [0, n) matching CPython Random._randbelow(n).
 * Uses k = n.bit_length() with rejection sampling until r < n.
 * Explicitly rejects n == 0 with BMT_ERR_EMPTY_RANGE.
 */
BMT_DEVICE static inline bmt_status_t bmt_below(bmt_state_t *state, uint64_t n, uint64_t *out) {
    if (state == NULL || out == NULL) {
        return BMT_ERR_NULL_POINTER;
    }
    if (n == 0) {
        return BMT_ERR_EMPTY_RANGE;
    }
    int k = bmt_bit_length_u64(n);
    uint64_t r = 0;
    do {
        bmt_status_t status = bmt_getbits64(state, k, &r);
        if (status != BMT_OK) {
            return status;
        }
    } while (r >= n);
    *out = r;
    return BMT_OK;
}

/* In-place Fisher-Yates shuffle matching CPython Random.shuffle(seq).
 * Loops i from n-1 down to 1 with j = _randbelow(i + 1).
 */
BMT_DEVICE static inline bmt_status_t bmt_shuffle_i32(bmt_state_t *state, int32_t *array, size_t n) {
    if (state == NULL || (n > 0 && array == NULL)) {
        return BMT_ERR_NULL_POINTER;
    }
    if (n <= 1) {
        return BMT_OK;
    }
    for (size_t i = n - 1; i > 0; i--) {
        uint64_t j = 0;
        bmt_status_t status = bmt_below(state, (uint64_t)(i + 1), &j);
        if (status != BMT_OK) {
            return status;
        }
        int32_t tmp = array[i];
        array[i] = array[j];
        array[j] = tmp;
    }
    return BMT_OK;
}

#endif /* BMT_RANDOM_SOURCE_H */
"""
