"""CUDA C++ source emitter for direct nonrecursive native builtins and bound methods.

Provides:
- SUPPORTED_BUILTIN_NAMES: Canonical tuple of directly supported builtins
  ('len', 'bool', 'int', 'float', 'range', 'iter', 'list', 'tuple', 'dict').
  ('next' is handled by the primary interpreter loop in cuda_vm.py).
- emit_builtin_source(intrinsic_names: tuple) -> str: Emits device C++ functions
  in namespace duel_rule_vm to be inserted immediately before call() and execute().

Implementation Scope and Limitations:
1. No claim of full VM coverage: Only the explicit supported builtins and bound
   mapping/list/sequence methods defined herein are handled natively on device.
2. No claim of CPython set iteration parity: Sets and frozensets (tags 21 and 22)
   can be queried for length and copied into lists/tuples, but general unordered set
   iteration semantics and set operations matching CPython are not claimed.
3. Generators and iterators in container constructors: Passing generators (tag 19)
   or iterators (tag 17) to list(), tuple(), or dict() is explicitly rejected with
   UNSUPPORTED_TYPE. Generators and iterators are never silently exhausted on CPU.
4. Range iteration: The range constructor allocates a tag 26 node storing [start, stop, step]
   as reference edges. Iterating over range objects requires integration with the existing
   iterator mechanism by the primary interpreter loop.
5. Strict arithmetic and finite bounds: Integer parsing and arithmetic enforce 64-bit
   signed integer overflow checks (setting ERROR_INT_OVERFLOW or UNSUPPORTED_TYPE).
   Float operations require finite values; non-finite floats trigger ERROR_NON_FINITE_FLOAT.
6. Pure device execution: Attribute name resolution is performed directly on device
   via device UTF-8 payload byte comparison without host computation, callbacks, or
   silent truncation.
"""

from __future__ import annotations

from typing import Sequence

SUPPORTED_BUILTIN_NAMES: tuple[str, ...] = (
    "len",
    "bool",
    "int",
    "float",
    "range",
    "iter",
    "list",
    "tuple",
    "dict",
)


def emit_builtin_source(intrinsic_names: tuple[str, ...] | Sequence[str] = ()) -> str:
    """Return CUDA C++ source for native builtins and bound methods in namespace duel_rule_vm.

    Static IDs for builtins are resolved from `intrinsic_names`. Absent builtins are assigned
    distinct negative sentinel IDs (-2001, -2002, ...) so that switch cases never suffer
    from duplicate value collisions.
    """
    names_tuple = tuple(intrinsic_names)
    injected_ids: dict[str, int] = {}
    for i, name in enumerate(SUPPORTED_BUILTIN_NAMES):
        if name in names_tuple:
            injected_ids[name] = names_tuple.index(name)
        else:
            injected_ids[name] = -2001 - i

    return f"""// --- VM Builtins and Bound Methods (generated by vm_builtins.py) ---

// Bound method metadata tag and Range tag
const int T_BOUND_METHOD = 34;
const int T_RANGE_NODE = 26;

// Bound method enumeration codes (stored in metadata node n[3])
enum BuiltinMethodCode {{
    METHOD_DICT_GET = 1,
    METHOD_DICT_KEYS = 2,
    METHOD_DICT_VALUES = 3,
    METHOD_DICT_ITEMS = 4,
    METHOD_DICT_SETDEFAULT = 5,
    METHOD_DICT_POP = 6,
    METHOD_DICT_UPDATE = 7,
    METHOD_DICT_COPY = 8,
    METHOD_LIST_APPEND = 9,
    METHOD_LIST_EXTEND = 10,
    METHOD_LIST_POP = 11,
    METHOD_LIST_INSERT = 12,
    METHOD_LIST_REMOVE = 13,
    METHOD_LIST_REVERSE = 14,
    METHOD_LIST_COPY = 15,
    METHOD_SEQ_INDEX = 16,
    METHOD_SEQ_COUNT = 17
}};

// Static intrinsic IDs (absent IDs receive distinct negative values)
const int NATIVE_LEN = {injected_ids['len']};
const int NATIVE_BOOL = {injected_ids['bool']};
const int NATIVE_INT = {injected_ids['int']};
const int NATIVE_FLOAT = {injected_ids['float']};
const int NATIVE_RANGE = {injected_ids['range']};
const int NATIVE_ITER = {injected_ids['iter']};
const int NATIVE_LIST = {injected_ids['list']};
const int NATIVE_TUPLE = {injected_ids['tuple']};
const int NATIVE_DICT = {injected_ids['dict']};

// Device UTF-8 string comparison against ASCII literal without host compute
__device__ inline bool vm_str_equals(Context* c, int str_ref, const char* lit, int lit_len) {{
    if (str_ref == MISSING) return false;
    NodeView nv;
    if (!get_node(&c->h, str_ref, &nv)) return false;
    if (nv.tag != TAG_STR || nv.count != lit_len) return false;
    const unsigned char* p = get_payload_ptr(&c->h, &nv);
    if (!p && lit_len > 0) return false;
    return (vm_memcmp(p, lit, lit_len) == 0);
}}

// Decimal string to signed 64-bit integer parser with strict overflow checking
__device__ inline int device_parse_int64_str(Context* c, int str_ref, long long* out_val) {{
    NodeView nv;
    if (!get_node(&c->h, str_ref, &nv)) {{ c->error = BAD_PROGRAM; return -1; }}
    const unsigned char* p = get_payload_ptr(&c->h, &nv);
    if (!p && nv.count > 0) {{ c->error = BAD_PROGRAM; return -1; }}
    int start = 0, end = nv.count;
    while (start < end && (p[start] == ' ' || p[start] == '\\t' || p[start] == '\\n' || p[start] == '\\r')) start++;
    while (end > start && (p[end - 1] == ' ' || p[end - 1] == '\\t' || p[end - 1] == '\\n' || p[end - 1] == '\\r')) end--;
    if (start >= end) {{ c->error = BAD_CALL; return -1; }}
    bool negative = false;
    if (p[start] == '+') {{
        start++;
    }} else if (p[start] == '-') {{
        negative = true;
        start++;
    }}
    if (start >= end) {{ c->error = BAD_CALL; return -1; }}
    unsigned long long limit_u = negative ? 9223372036854775808ULL : 9223372036854775807ULL;
    unsigned long long val_u = 0;
    for (int i = start; i < end; i++) {{
        if (p[i] < '0' || p[i] > '9') {{ c->error = BAD_CALL; return -1; }}
        int d = (int)(p[i] - '0');
        if (val_u > (limit_u - (unsigned long long)d) / 10ULL) {{
            c->h.error = ERROR_INT_OVERFLOW;
            return -1;
        }}
        val_u = val_u * 10ULL + (unsigned long long)d;
    }}
    if (negative) {{
        if (val_u == 9223372036854775808ULL) {{
            *out_val = (-9223372036854775807LL - 1LL);
        }} else {{
            *out_val = -(long long)val_u;
        }}
    }} else {{
        *out_val = (long long)val_u;
    }}
    return 0;
}}

// String to finite double parser with bounds verification
__device__ inline int device_parse_float64_str(Context* c, int str_ref, double* out_val) {{
    NodeView nv;
    if (!get_node(&c->h, str_ref, &nv)) {{ c->error = BAD_PROGRAM; return -1; }}
    const unsigned char* p = get_payload_ptr(&c->h, &nv);
    if (!p && nv.count > 0) {{ c->error = BAD_PROGRAM; return -1; }}
    int start = 0, end = nv.count;
    while (start < end && (p[start] == ' ' || p[start] == '\\t' || p[start] == '\\n' || p[start] == '\\r')) start++;
    while (end > start && (p[end - 1] == ' ' || p[end - 1] == '\\t' || p[end - 1] == '\\n' || p[end - 1] == '\\r')) end--;
    if (start >= end) {{ c->error = BAD_CALL; return -1; }}
    bool neg = false;
    if (p[start] == '+') {{
        start++;
    }} else if (p[start] == '-') {{
        neg = true;
        start++;
    }}
    if (start >= end) {{ c->error = BAD_CALL; return -1; }}
    double val = 0.0;
    bool has_digits = false;
    while (start < end && p[start] >= '0' && p[start] <= '9') {{
        val = val * 10.0 + (double)(p[start] - '0');
        has_digits = true;
        start++;
    }}
    if (start < end && p[start] == '.') {{
        start++;
        double frac = 0.1;
        while (start < end && p[start] >= '0' && p[start] <= '9') {{
            val += (double)(p[start] - '0') * frac;
            frac *= 0.1;
            has_digits = true;
            start++;
        }}
    }}
    if (!has_digits) {{ c->error = BAD_CALL; return -1; }}
    if (start < end && (p[start] == 'e' || p[start] == 'E')) {{
        start++;
        if (start >= end) {{ c->error = BAD_CALL; return -1; }}
        bool exp_neg = false;
        if (p[start] == '+') start++;
        else if (p[start] == '-') {{ exp_neg = true; start++; }}
        if (start >= end || p[start] < '0' || p[start] > '9') {{ c->error = BAD_CALL; return -1; }}
        int exp_val = 0;
        while (start < end && p[start] >= '0' && p[start] <= '9') {{
            exp_val = exp_val * 10 + (int)(p[start] - '0');
            if (exp_val > 400) break;
            start++;
        }}
        double scale = 1.0;
        for (int e = 0; e < exp_val; e++) {{
            if (exp_neg) scale /= 10.0;
            else scale *= 10.0;
        }}
        val *= scale;
    }}
    if (start != end) {{ c->error = BAD_CALL; return -1; }}
    if (neg) val = -val;
    if (!vm_isfinite(val)) {{ c->h.error = ERROR_NON_FINITE_FLOAT; return -1; }}
    *out_val = val;
    return 0;
}}

// In-place direct pop from arbitrary index in mutable list
__device__ inline int device_list_pop_at(Context* c, int list_ref, int index, int* out_val) {{
    if (list_ref < 0) {{ c->h.error = ERROR_CONSTANT_WRITE; return -1; }}
    const int* n = node(c, list_ref);
    if (!n || n[0] != TAG_LIST) {{ c->error = UNSUPPORTED_TYPE; return -1; }}
    int count = n[2];
    if (count <= 0) {{ c->h.error = ERROR_INDEX_OUT_OF_BOUNDS; return -1; }}
    if (index < 0) index = count + index;
    if (index < 0 || index >= count) {{ c->h.error = ERROR_INDEX_OUT_OF_BOUNDS; return -1; }}
    int offset = n[1];
    *out_val = c->h.edges[(offset + index) * 2 + 0];
    for (int i = index; i < count - 1; i++) {{
        c->h.edges[(offset + i) * 2 + 0] = c->h.edges[(offset + i + 1) * 2 + 0];
        c->h.edges[(offset + i) * 2 + 1] = -1;
    }}
    c->h.nodes[list_ref * 4 + 2] = count - 1;
    if (offset + count == c->h.counts[1]) {{
        c->h.counts[1]--;
    }}
    return 0;
}}

// Insert element at normalized index with edge reallocation if required
__device__ inline int device_list_insert(Context* c, int list_ref, int index, int item_ref) {{
    if (list_ref < 0) {{ c->h.error = ERROR_CONSTANT_WRITE; return -1; }}
    const int* n = node(c, list_ref);
    if (!n || n[0] != TAG_LIST) {{ c->error = UNSUPPORTED_TYPE; return -1; }}
    int old_count = n[2];
    int old_offset = n[1];
    if (index < 0) {{ index += old_count; if (index < 0) index = 0; }}
    if (index > old_count) index = old_count;
    if (old_offset + old_count == c->h.counts[1]) {{
        if (c->h.counts[1] + 1 > c->h.max_edges) {{ c->h.error = ERROR_EDGE_CAPACITY; return -1; }}
        for (int i = old_count; i > index; i--) {{
            c->h.edges[(old_offset + i) * 2 + 0] = c->h.edges[(old_offset + i - 1) * 2 + 0];
            c->h.edges[(old_offset + i) * 2 + 1] = -1;
        }}
        c->h.edges[(old_offset + index) * 2 + 0] = item_ref;
        c->h.edges[(old_offset + index) * 2 + 1] = -1;
        c->h.counts[1]++;
        c->h.nodes[list_ref * 4 + 2] = old_count + 1;
        return 0;
    }} else {{
        int new_count = old_count + 1;
        if (c->h.counts[1] + new_count > c->h.max_edges) {{ c->h.error = ERROR_EDGE_CAPACITY; return -1; }}
        int new_offset = c->h.counts[1];
        for (int i = 0; i < index; i++) {{
            c->h.edges[(new_offset + i) * 2 + 0] = c->h.edges[(old_offset + i) * 2 + 0];
            c->h.edges[(new_offset + i) * 2 + 1] = -1;
        }}
        c->h.edges[(new_offset + index) * 2 + 0] = item_ref;
        c->h.edges[(new_offset + index) * 2 + 1] = -1;
        for (int i = index; i < old_count; i++) {{
            c->h.edges[(new_offset + i + 1) * 2 + 0] = c->h.edges[(old_offset + i) * 2 + 0];
            c->h.edges[(new_offset + i + 1) * 2 + 1] = -1;
        }}
        c->h.counts[1] += new_count;
        c->h.nodes[list_ref * 4 + 1] = new_offset;
        c->h.nodes[list_ref * 4 + 2] = new_count;
        return 0;
    }}
}}

// Remove first occurrence of item matching key_equal from mutable list
__device__ inline int device_list_remove(Context* c, int list_ref, int item_ref) {{
    if (list_ref < 0) {{ c->h.error = ERROR_CONSTANT_WRITE; return -1; }}
    const int* n = node(c, list_ref);
    if (!n || n[0] != TAG_LIST) {{ c->error = UNSUPPORTED_TYPE; return -1; }}
    int count = n[2];
    int offset = n[1];
    int target_idx = -1;
    for (int i = 0; i < count; i++) {{
        int elem = c->h.edges[(offset + i) * 2 + 0];
        if (vm_equal(c, elem, item_ref)) {{
            target_idx = i;
            break;
        }}
        if (c->h.error != ERROR_OK) return -1;
    }}
    if (target_idx < 0) {{
        c->error = BAD_CALL;
        return -1;
    }}
    for (int i = target_idx; i < count - 1; i++) {{
        c->h.edges[(offset + i) * 2 + 0] = c->h.edges[(offset + i + 1) * 2 + 0];
        c->h.edges[(offset + i) * 2 + 1] = -1;
    }}
    c->h.nodes[list_ref * 4 + 2] = count - 1;
    if (offset + count == c->h.counts[1]) {{
        c->h.counts[1]--;
    }}
    return 0;
}}

// In-place list reverse
__device__ inline int device_list_reverse(Context* c, int list_ref) {{
    if (list_ref < 0) {{ c->h.error = ERROR_CONSTANT_WRITE; return -1; }}
    const int* n = node(c, list_ref);
    if (!n || n[0] != TAG_LIST) {{ c->error = UNSUPPORTED_TYPE; return -1; }}
    int count = n[2];
    int offset = n[1];
    for (int i = 0; i < count / 2; i++) {{
        int tmp = c->h.edges[(offset + i) * 2 + 0];
        c->h.edges[(offset + i) * 2 + 0] = c->h.edges[(offset + count - 1 - i) * 2 + 0];
        c->h.edges[(offset + count - 1 - i) * 2 + 0] = tmp;
    }}
    return 0;
}}

// Dictionary update: safely handles self-update and updates from mapping or pair sequences
__device__ inline int device_dict_update(Context* c, int dict_ref, int other_ref) {{
    if (dict_ref < 0) {{ c->h.error = ERROR_CONSTANT_WRITE; return -1; }}
    if (dict_ref == other_ref) {{
        return 0;
    }}
    const int* on = node(c, other_ref);
    if (!on) {{ c->error = BAD_CALL; return -1; }}
    int otag = on[0];
    if (otag == TAG_DICT || (otag >= 8 && otag <= 10)) {{
        int count = on[2];
        for (int i = 0; i < count; i++) {{
            int k = edge(c, other_ref, i, 0);
            int v = edge(c, other_ref, i, 1);
            if (dict_set(&c->h, dict_ref, k, v) != 0) return -1;
        }}
        return 0;
    }} else if (otag == TAG_LIST || otag == TAG_TUPLE) {{
        int count = on[2];
        for (int i = 0; i < count; i++) {{
            int item = edge(c, other_ref, i, 0);
            const int* in = node(c, item);
            if (!in || (in[0] != TAG_LIST && in[0] != TAG_TUPLE) || in[2] != 2) {{
                c->error = BAD_CALL;
                return -1;
            }}
            int k = edge(c, item, 0, 0);
            int v = edge(c, item, 1, 0);
            if (dict_set(&c->h, dict_ref, k, v) != 0) return -1;
        }}
        return 0;
    }}
    c->error = UNSUPPORTED_TYPE;
    return -1;
}}

// Attribute lookup on native/mapping/list/tuple containers.
// Returns metadata node tag 34 with n[1]=owner and n[3]=method_code.
// Unsupported attributes return MISSING with no error set.
__device__ inline int builtin_attribute(Context* c, int owner, int name) {{
    if (owner == MISSING || name == MISSING) return MISSING;
    int otag = kind(c, owner);
    if (otag == TAG_DICT || (otag >= 8 && otag <= 10)) {{
        if (vm_str_equals(c, name, "get", 3)) {{
            return meta(c, 34, owner, 0, METHOD_DICT_GET);
        }} else if (vm_str_equals(c, name, "keys", 4)) {{
            return meta(c, 34, owner, 0, METHOD_DICT_KEYS);
        }} else if (vm_str_equals(c, name, "values", 6)) {{
            return meta(c, 34, owner, 0, METHOD_DICT_VALUES);
        }} else if (vm_str_equals(c, name, "items", 5)) {{
            return meta(c, 34, owner, 0, METHOD_DICT_ITEMS);
        }} else if (vm_str_equals(c, name, "setdefault", 10)) {{
            return meta(c, 34, owner, 0, METHOD_DICT_SETDEFAULT);
        }} else if (vm_str_equals(c, name, "pop", 3)) {{
            return meta(c, 34, owner, 0, METHOD_DICT_POP);
        }} else if (vm_str_equals(c, name, "update", 6)) {{
            return meta(c, 34, owner, 0, METHOD_DICT_UPDATE);
        }} else if (vm_str_equals(c, name, "copy", 4)) {{
            return meta(c, 34, owner, 0, METHOD_DICT_COPY);
        }}
        return MISSING;
    }} else if (otag == TAG_LIST) {{
        if (vm_str_equals(c, name, "append", 6)) {{
            return meta(c, 34, owner, 0, METHOD_LIST_APPEND);
        }} else if (vm_str_equals(c, name, "extend", 6)) {{
            return meta(c, 34, owner, 0, METHOD_LIST_EXTEND);
        }} else if (vm_str_equals(c, name, "pop", 3)) {{
            return meta(c, 34, owner, 0, METHOD_LIST_POP);
        }} else if (vm_str_equals(c, name, "insert", 6)) {{
            return meta(c, 34, owner, 0, METHOD_LIST_INSERT);
        }} else if (vm_str_equals(c, name, "remove", 6)) {{
            return meta(c, 34, owner, 0, METHOD_LIST_REMOVE);
        }} else if (vm_str_equals(c, name, "reverse", 7)) {{
            return meta(c, 34, owner, 0, METHOD_LIST_REVERSE);
        }} else if (vm_str_equals(c, name, "copy", 4)) {{
            return meta(c, 34, owner, 0, METHOD_LIST_COPY);
        }} else if (vm_str_equals(c, name, "index", 5)) {{
            return meta(c, 34, owner, 0, METHOD_SEQ_INDEX);
        }} else if (vm_str_equals(c, name, "count", 5)) {{
            return meta(c, 34, owner, 0, METHOD_SEQ_COUNT);
        }}
        return MISSING;
    }} else if (otag == TAG_TUPLE) {{
        if (vm_str_equals(c, name, "index", 5)) {{
            return meta(c, 34, owner, 0, METHOD_SEQ_INDEX);
        }} else if (vm_str_equals(c, name, "count", 5)) {{
            return meta(c, 34, owner, 0, METHOD_SEQ_COUNT);
        }}
        return MISSING;
    }}
    return MISSING;
}}

// Directly call a native builtin (tag 15) or bound method (tag 34).
// Returns 1 if handled (successful or errored via c->error/c->h.error), 0 if unhandled.
// Result reference is written to *out.
__device__ inline int native_builtin_call(Context* c, int callable, const int* args, int nargs, int* out) {{
    const int* n = node(c, callable);
    if (!n) return 0;
    int callee_tag = n[0];

    if (callee_tag == T_NATIVE) {{
        int intrinsic_id = n[3];
        switch (intrinsic_id) {{
            case NATIVE_LEN: {{
                if (NATIVE_LEN < 0) return 0;
                if (nargs != 1) {{ c->error = BAD_CALL; return 1; }}
                int target = args[0];
                int ttag = kind(c, target);
                if (ttag == TAG_STR) {{
                    int chars = str_char_length(&c->h, target);
                    if (chars < 0) return 1;
                    *out = make_int64(&c->h, (long long)chars);
                    return 1;
                }} else if (ttag == TAG_LIST || ttag == TAG_TUPLE || ttag == TAG_DICT ||
                           (ttag >= 8 && ttag <= 10) || ttag == 21 || ttag == 22) {{
                    const int* tn = node(c, target);
                    if (!tn) {{ c->error = BAD_PROGRAM; return 1; }}
                    *out = make_int64(&c->h, (long long)tn[2]);
                    return 1;
                }} else if (ttag == T_RANGE_NODE) {{
                    int r_start = edge(c, target, 0, 0);
                    int r_stop = edge(c, target, 1, 0);
                    int r_step = edge(c, target, 2, 0);
                    long long st = 0, sp = 0, stp = 0;
                    if (read_int64(&c->h, r_start, &st) != 0 ||
                        read_int64(&c->h, r_stop, &sp) != 0 ||
                        read_int64(&c->h, r_step, &stp) != 0) return 1;
                    long long range_len = range_size(c, target);
                    *out = make_int64(&c->h, range_len);
                    return 1;
                }} else {{
                    c->error = UNSUPPORTED_TYPE;
                    return 1;
                }}
            }}
            case NATIVE_BOOL: {{
                if (NATIVE_BOOL < 0) return 0;
                if (nargs == 0) {{
                    *out = FALSE_REF;
                    return 1;
                }}
                if (nargs != 1) {{ c->error = BAD_CALL; return 1; }}
                int t = truth_value(c, args[0]);
                *out = t ? TRUE_REF : FALSE_REF;
                return 1;
            }}
            case NATIVE_INT: {{
                if (NATIVE_INT < 0) return 0;
                if (nargs == 0) {{
                    *out = make_int64(&c->h, 0);
                    return 1;
                }}
                if (nargs != 1) {{ c->error = BAD_CALL; return 1; }}
                int target = args[0];
                int ttag = kind(c, target);
                if (ttag == TAG_INT) {{
                    *out = target;
                    return 1;
                }} else if (ttag == TAG_BOOL) {{
                    const int* bn = node(c, target);
                    *out = make_int64(&c->h, bn ? (bn[3] ? 1LL : 0LL) : 0LL);
                    return 1;
                }} else if (ttag == TAG_FLOAT) {{
                    double f = 0.0;
                    if (read_float64(&c->h, target, &f) != 0) return 1;
                    if (!vm_isfinite(f)) {{ c->h.error = ERROR_NON_FINITE_FLOAT; return 1; }}
                    if (f < -9223372036854775808.0 || f >= 9223372036854775808.0) {{
                        c->h.error = ERROR_INT_OVERFLOW;
                        return 1;
                    }}
                    long long truncated = (long long)f;
                    *out = make_int64(&c->h, truncated);
                    return 1;
                }} else if (ttag == TAG_STR) {{
                    long long parsed = 0;
                    if (device_parse_int64_str(c, target, &parsed) != 0) return 1;
                    *out = make_int64(&c->h, parsed);
                    return 1;
                }} else {{
                    c->error = UNSUPPORTED_TYPE;
                    return 1;
                }}
            }}
            case NATIVE_FLOAT: {{
                if (NATIVE_FLOAT < 0) return 0;
                if (nargs == 0) {{
                    *out = make_float64(&c->h, 0.0);
                    return 1;
                }}
                if (nargs != 1) {{ c->error = BAD_CALL; return 1; }}
                int target = args[0];
                int ttag = kind(c, target);
                if (ttag == TAG_FLOAT) {{
                    *out = target;
                    return 1;
                }} else if (ttag == TAG_INT) {{
                    long long iv = 0;
                    if (read_int64(&c->h, target, &iv) != 0) return 1;
                    *out = make_float64(&c->h, (double)iv);
                    return 1;
                }} else if (ttag == TAG_BOOL) {{
                    const int* bn = node(c, target);
                    *out = make_float64(&c->h, bn ? (bn[3] ? 1.0 : 0.0) : 0.0);
                    return 1;
                }} else if (ttag == TAG_STR) {{
                    double parsed = 0.0;
                    if (device_parse_float64_str(c, target, &parsed) != 0) return 1;
                    *out = make_float64(&c->h, parsed);
                    return 1;
                }} else {{
                    c->error = UNSUPPORTED_TYPE;
                    return 1;
                }}
            }}
            case NATIVE_RANGE: {{
                if (NATIVE_RANGE < 0) return 0;
                if (nargs < 1 || nargs > 3) {{ c->error = BAD_CALL; return 1; }}
                int start_ref, stop_ref, step_ref;
                if (nargs == 1) {{
                    start_ref = make_int64(&c->h, 0);
                    stop_ref = args[0];
                    step_ref = make_int64(&c->h, 1);
                }} else if (nargs == 2) {{
                    start_ref = args[0];
                    stop_ref = args[1];
                    step_ref = make_int64(&c->h, 1);
                }} else {{
                    start_ref = args[0];
                    stop_ref = args[1];
                    step_ref = args[2];
                }}
                long long st = 0, sp = 0, stp = 0;
                if (read_int64(&c->h, start_ref, &st) != 0 ||
                    read_int64(&c->h, stop_ref, &sp) != 0 ||
                    read_int64(&c->h, step_ref, &stp) != 0) {{
                    c->error = BAD_CALL;
                    return 1;
                }}
                if (stp == 0) {{
                    c->error = BAD_CALL;
                    return 1;
                }}
                if (c->h.counts[1] + 3 > c->h.max_edges) {{
                    c->h.error = ERROR_EDGE_CAPACITY;
                    return 1;
                }}
                int e_start = c->h.counts[1];
                c->h.edges[(e_start + 0) * 2 + 0] = start_ref;
                c->h.edges[(e_start + 0) * 2 + 1] = -1;
                c->h.edges[(e_start + 1) * 2 + 0] = stop_ref;
                c->h.edges[(e_start + 1) * 2 + 1] = -1;
                c->h.edges[(e_start + 2) * 2 + 0] = step_ref;
                c->h.edges[(e_start + 2) * 2 + 1] = -1;
                c->h.counts[1] += 3;
                int r_node = meta(c, T_RANGE_NODE, e_start, 3, 0);
                if (r_node == MISSING) return 1;
                *out = r_node;
                return 1;
            }}
            case NATIVE_ITER: {{
                if (NATIVE_ITER < 0) return 0;
                if (nargs != 1) {{ c->error = BAD_CALL; return 1; }}
                int it = iterator(c, args[0]);
                if (it == MISSING) return 1;
                *out = it;
                return 1;
            }}
            case NATIVE_LIST: {{
                if (NATIVE_LIST < 0) return 0;
                if (nargs == 0) {{
                    *out = make_list(&c->h);
                    return 1;
                }}
                if (nargs != 1) {{ c->error = BAD_CALL; return 1; }}
                int src = args[0];
                int stag = kind(c, src);
                if (stag == T_GEN || stag == T_ITER) {{
                    c->error = UNSUPPORTED_TYPE;
                    return 1;
                }}
                if (stag == TAG_LIST || stag == TAG_TUPLE || stag == 21 || stag == 22) {{
                    int res = make_list(&c->h);
                    if (res < 0) return 1;
                    int cnt = length(c, src);
                    for (int i = 0; i < cnt; i++) {{
                        if (list_append(&c->h, res, edge(c, src, i, 0)) != 0) return 1;
                    }}
                    *out = res;
                    return 1;
                }} else if (stag == TAG_DICT || (stag >= 8 && stag <= 10)) {{
                    int res = make_list(&c->h);
                    if (res < 0) return 1;
                    int cnt = length(c, src);
                    for (int i = 0; i < cnt; i++) {{
                        if (list_append(&c->h, res, edge(c, src, i, 0)) != 0) return 1;
                    }}
                    *out = res;
                    return 1;
                }} else if (stag == T_RANGE_NODE) {{
                    int r_start = edge(c, src, 0, 0);
                    int r_stop = edge(c, src, 1, 0);
                    int r_step = edge(c, src, 2, 0);
                    long long st = 0, sp = 0, stp = 0;
                    if (read_int64(&c->h, r_start, &st) != 0 ||
                        read_int64(&c->h, r_stop, &sp) != 0 ||
                        read_int64(&c->h, r_step, &stp) != 0) return 1;
                    int res = make_list(&c->h);
                    if (res < 0) return 1;
                    long long count=range_size(c,src);
                    for(long long i=0;i<count;i++) {{
                        long long v=(long long)((unsigned long long)st+(unsigned long long)i*(unsigned long long)stp);
                        int ir=make_int64(&c->h,v);if(ir<0||list_append(&c->h,res,ir)!=0)return 1;
                    }}
                    *out = res;
                    return 1;
                }} else {{
                    c->error = UNSUPPORTED_TYPE;
                    return 1;
                }}
            }}
            case NATIVE_TUPLE: {{
                if (NATIVE_TUPLE < 0) return 0;
                if (nargs == 0) {{
                    *out = make_tuple(&c->h, 0, 0);
                    return 1;
                }}
                if (nargs != 1) {{ c->error = BAD_CALL; return 1; }}
                int src = args[0];
                int stag = kind(c, src);
                if (stag == T_GEN || stag == T_ITER) {{
                    c->error = UNSUPPORTED_TYPE;
                    return 1;
                }}
                if (stag == TAG_TUPLE) {{
                    *out = src;
                    return 1;
                }} else if (stag == TAG_LIST || stag == 21 || stag == 22 ||
                           stag == TAG_DICT || (stag >= 8 && stag <= 10)) {{
                    int cnt = length(c, src);
                    if (cnt == 0) {{
                        *out = make_tuple(&c->h, 0, 0);
                        return 1;
                    }}
                    if (c->h.counts[0] + 1 > c->h.max_nodes) {{ c->h.error = ERROR_NODE_CAPACITY; return 1; }}
                    if (c->h.counts[1] + cnt > c->h.max_edges) {{ c->h.error = ERROR_EDGE_CAPACITY; return 1; }}
                    int start_edge = c->h.counts[1];
                    for (int i = 0; i < cnt; i++) {{
                        c->h.edges[(start_edge + i) * 2 + 0] = edge(c, src, i, 0);
                        c->h.edges[(start_edge + i) * 2 + 1] = -1;
                    }}
                    c->h.counts[1] += cnt;
                    int ref = c->h.counts[0]++;
                    c->h.nodes[ref * 4 + 0] = TAG_TUPLE;
                    c->h.nodes[ref * 4 + 1] = start_edge;
                    c->h.nodes[ref * 4 + 2] = cnt;
                    c->h.nodes[ref * 4 + 3] = 0;
                    *out = ref;
                    return 1;
                }} else {{
                    c->error = UNSUPPORTED_TYPE;
                    return 1;
                }}
            }}
            case NATIVE_DICT: {{
                if (NATIVE_DICT < 0) return 0;
                if (nargs == 0) {{
                    *out = make_dict(&c->h);
                    return 1;
                }}
                if (nargs != 1) {{ c->error = BAD_CALL; return 1; }}
                int src = args[0];
                int stag = kind(c, src);
                if (stag == T_GEN || stag == T_ITER) {{
                    c->error = UNSUPPORTED_TYPE;
                    return 1;
                }}
                if (stag == TAG_DICT || (stag >= 8 && stag <= 10)) {{
                    int res = make_dict(&c->h);
                    if (res < 0) return 1;
                    int cnt = length(c, src);
                    for (int i = 0; i < cnt; i++) {{
                        int k = edge(c, src, i, 0);
                        int v = edge(c, src, i, 1);
                        if (dict_set(&c->h, res, k, v) != 0) return 1;
                    }}
                    *out = res;
                    return 1;
                }} else if (stag == TAG_LIST || stag == TAG_TUPLE) {{
                    int res = make_dict(&c->h);
                    if (res < 0) return 1;
                    int cnt = length(c, src);
                    for (int i = 0; i < cnt; i++) {{
                        int pair = edge(c, src, i, 0);
                        const int* pn = node(c, pair);
                        if (!pn || (pn[0] != TAG_LIST && pn[0] != TAG_TUPLE) || pn[2] != 2) {{
                            c->error = BAD_CALL;
                            return 1;
                        }}
                        int k = edge(c, pair, 0, 0);
                        int v = edge(c, pair, 1, 0);
                        if (dict_set(&c->h, res, k, v) != 0) return 1;
                    }}
                    *out = res;
                    return 1;
                }} else {{
                    c->error = UNSUPPORTED_TYPE;
                    return 1;
                }}
            }}
            default:
                return 0;
        }}
    }} else if (callee_tag == T_BOUND_METHOD) {{
        int owner = n[1];
        int method_code = n[3];
        switch (method_code) {{
            case METHOD_DICT_GET: {{
                if (nargs < 1 || nargs > 2) {{ c->error = BAD_CALL; return 1; }}
                int def_val = (nargs == 2) ? args[1] : NIL;
                int res = dict_get(&c->h, owner, args[0], def_val);
                if (c->h.error != ERROR_OK) return 1;
                *out = res;
                return 1;
            }}
            case METHOD_DICT_KEYS: {{
                if (nargs != 0) {{ c->error = BAD_CALL; return 1; }}
                int res = make_list(&c->h);
                if (res < 0) return 1;
                int cnt = length(c, owner);
                for (int i = 0; i < cnt; i++) {{
                    if (list_append(&c->h, res, edge(c, owner, i, 0)) != 0) return 1;
                }}
                *out = res;
                return 1;
            }}
            case METHOD_DICT_VALUES: {{
                if (nargs != 0) {{ c->error = BAD_CALL; return 1; }}
                int res = make_list(&c->h);
                if (res < 0) return 1;
                int cnt = length(c, owner);
                for (int i = 0; i < cnt; i++) {{
                    if (list_append(&c->h, res, edge(c, owner, i, 1)) != 0) return 1;
                }}
                *out = res;
                return 1;
            }}
            case METHOD_DICT_ITEMS: {{
                if (nargs != 0) {{ c->error = BAD_CALL; return 1; }}
                int res = make_list(&c->h);
                if (res < 0) return 1;
                int cnt = length(c, owner);
                for (int i = 0; i < cnt; i++) {{
                    int pair[2] = {{ edge(c, owner, i, 0), edge(c, owner, i, 1) }};
                    int tup = make_tuple(&c->h, pair, 2);
                    if (tup < 0 || list_append(&c->h, res, tup) != 0) return 1;
                }}
                *out = res;
                return 1;
            }}
            case METHOD_DICT_SETDEFAULT: {{
                if (nargs < 1 || nargs > 2) {{ c->error = BAD_CALL; return 1; }}
                int idx = dict_find(&c->h, owner, args[0]);
                if (c->h.error != ERROR_OK) return 1;
                if (idx >= 0) {{
                    *out = edge(c, owner, idx, 1);
                    return 1;
                }}
                if (owner < 0) {{ c->h.error = ERROR_CONSTANT_WRITE; return 1; }}
                int def_val = (nargs == 2) ? args[1] : NIL;
                if (dict_set(&c->h, owner, args[0], def_val) != 0) return 1;
                *out = def_val;
                return 1;
            }}
            case METHOD_DICT_POP: {{
                if (nargs < 1 || nargs > 2) {{ c->error = BAD_CALL; return 1; }}
                if (owner < 0) {{ c->h.error = ERROR_CONSTANT_WRITE; return 1; }}
                int idx = dict_find(&c->h, owner, args[0]);
                if (c->h.error != ERROR_OK) return 1;
                if (idx >= 0) {{
                    int val = edge(c, owner, idx, 1);
                    if (dict_delete(&c->h, owner, args[0]) != 0) return 1;
                    *out = val;
                    return 1;
                }}
                if (nargs == 2) {{
                    *out = args[1];
                    return 1;
                }}
                c->h.error = ERROR_KEY_NOT_FOUND;
                return 1;
            }}
            case METHOD_DICT_UPDATE: {{
                if (nargs != 1) {{ c->error = BAD_CALL; return 1; }}
                if (device_dict_update(c, owner, args[0]) != 0) return 1;
                *out = NIL;
                return 1;
            }}
            case METHOD_DICT_COPY: {{
                if (nargs != 0) {{ c->error = BAD_CALL; return 1; }}
                int res = make_dict(&c->h);
                if (res < 0) return 1;
                int cnt = length(c, owner);
                for (int i = 0; i < cnt; i++) {{
                    int k = edge(c, owner, i, 0);
                    int v = edge(c, owner, i, 1);
                    if (dict_set(&c->h, res, k, v) != 0) return 1;
                }}
                *out = res;
                return 1;
            }}
            case METHOD_LIST_APPEND: {{
                if (nargs != 1) {{ c->error = BAD_CALL; return 1; }}
                if (list_append(&c->h, owner, args[0]) != 0) return 1;
                *out = NIL;
                return 1;
            }}
            case METHOD_LIST_EXTEND: {{
                if (nargs != 1) {{ c->error = BAD_CALL; return 1; }}
                if (owner < 0) {{ c->h.error = ERROR_CONSTANT_WRITE; return 1; }}
                int src = args[0];
                if (src == owner) {{
                    int init_cnt = length(c, owner);
                    for (int i = 0; i < init_cnt; i++) {{
                        int elem = edge(c, owner, i, 0);
                        if (list_append(&c->h, owner, elem) != 0) return 1;
                    }}
                    *out = NIL;
                    return 1;
                }}
                int stag = kind(c, src);
                if (stag == TAG_LIST || stag == TAG_TUPLE || stag == 21 || stag == 22) {{
                    int cnt = length(c, src);
                    for (int i = 0; i < cnt; i++) {{
                        if (list_append(&c->h, owner, edge(c, src, i, 0)) != 0) return 1;
                    }}
                    *out = NIL;
                    return 1;
                }} else if (stag == TAG_DICT || (stag >= 8 && stag <= 10)) {{
                    int cnt = length(c, src);
                    for (int i = 0; i < cnt; i++) {{
                        if (list_append(&c->h, owner, edge(c, src, i, 0)) != 0) return 1;
                    }}
                    *out = NIL;
                    return 1;
                }} else {{
                    c->error = UNSUPPORTED_TYPE;
                    return 1;
                }}
            }}
            case METHOD_LIST_POP: {{
                if (nargs > 1) {{ c->error = BAD_CALL; return 1; }}
                int val = MISSING;
                if (nargs == 0) {{
                    if (list_pop(&c->h, owner, &val) != 0) return 1;
                }} else {{
                    long long idx_v = 0;
                    if (read_int64(&c->h, args[0], &idx_v) != 0) return 1;
                    if (idx_v < (-2147483647LL-1) || idx_v > 2147483647LL) {{ c->error=UNSUPPORTED_TYPE;return 1; }}
                    if (device_list_pop_at(c, owner, (int)idx_v, &val) != 0) return 1;
                }}
                *out = val;
                return 1;
            }}
            case METHOD_LIST_INSERT: {{
                if (nargs != 2) {{ c->error = BAD_CALL; return 1; }}
                long long idx_v = 0;
                if (read_int64(&c->h, args[0], &idx_v) != 0) return 1;
                int count=length(c,owner);if(idx_v>count)idx_v=count;if(idx_v<-(long long)count)idx_v=0;
                if (device_list_insert(c, owner, (int)idx_v, args[1]) != 0) return 1;
                *out = NIL;
                return 1;
            }}
            case METHOD_LIST_REMOVE: {{
                if (nargs != 1) {{ c->error = BAD_CALL; return 1; }}
                if (device_list_remove(c, owner, args[0]) != 0) return 1;
                *out = NIL;
                return 1;
            }}
            case METHOD_LIST_REVERSE: {{
                if (nargs != 0) {{ c->error = BAD_CALL; return 1; }}
                if (device_list_reverse(c, owner) != 0) return 1;
                *out = NIL;
                return 1;
            }}
            case METHOD_LIST_COPY: {{
                if (nargs != 0) {{ c->error = BAD_CALL; return 1; }}
                int res = make_list(&c->h);
                if (res < 0) return 1;
                int cnt = length(c, owner);
                for (int i = 0; i < cnt; i++) {{
                    if (list_append(&c->h, res, edge(c, owner, i, 0)) != 0) return 1;
                }}
                *out = res;
                return 1;
            }}
            case METHOD_SEQ_INDEX: {{
                if (nargs < 1 || nargs > 3) {{ c->error = BAD_CALL; return 1; }}
                int len = length(c, owner);
                int start_idx = 0;
                int end_idx = len;
                if (nargs >= 2) {{
                    long long s = 0;
                    if (read_int64(&c->h, args[1], &s) != 0) return 1;
                    if (s < 0) s += len;
                    if (s < 0) s = 0;
                    if (s > len) s = len;
                    start_idx = (int)s;
                }}
                if (nargs == 3) {{
                    long long e = 0;
                    if (read_int64(&c->h, args[2], &e) != 0) return 1;
                    if (e < 0) e += len;
                    if (e < 0) e = 0;
                    if (e > len) e = len;
                    end_idx = (int)e;
                }}
                int found = -1;
                for (int i = start_idx; i < end_idx; i++) {{
                    int elem = edge(c, owner, i, 0);
                    if (vm_equal(c, elem, args[0])) {{
                        found = i;
                        break;
                    }}
                    if (c->h.error != ERROR_OK) return 1;
                }}
                if (found < 0) {{
                    c->error = BAD_CALL;
                    return 1;
                }}
                *out = make_int64(&c->h, (long long)found);
                return 1;
            }}
            case METHOD_SEQ_COUNT: {{
                if (nargs != 1) {{ c->error = BAD_CALL; return 1; }}
                int len = length(c, owner);
                long long cnt = 0;
                for (int i = 0; i < len; i++) {{
                    int elem = edge(c, owner, i, 0);
                    if (vm_equal(c, elem, args[0])) {{
                        cnt++;
                    }}
                    if (c->h.error != ERROR_OK) return 1;
                }}
                *out = make_int64(&c->h, cnt);
                return 1;
            }}
            default:
                c->error = BAD_CALL;
                return 1;
        }}
    }}
    return 0;
}}
"""
