"""CUDA device mutable graph heap primitives for batched duel states.

Provides:
- Schema tag constants and ABI definitions matching schema.PackedStateBatch.
- Error codes for capacity, type, ref, int overflow, constant writes, and workstack limits.
- emit_vm_heap_source() returning self-contained CUDA C++ namespace duel_vm_heap source.

Importing this module does not import PyTorch or initialize CUDA.
"""

from __future__ import annotations

import hashlib
from typing import Mapping

# Node tag constants matching schema.py (int32)
TAG_NONE: int = 0
TAG_BOOL: int = 1
TAG_INT: int = 2
TAG_FLOAT: int = 3
TAG_STR: int = 4
TAG_LIST: int = 5
TAG_TUPLE: int = 6
TAG_DICT: int = 7
TAG_PLAYER_ENTITY: int = 8
TAG_CHARACTER_ENTITY: int = 9
TAG_CARD_ENTITY: int = 10

VALID_TAGS: frozenset[int] = frozenset(range(11))

# Error codes matching C++ enum duel_vm_heap::ErrorCode
ERROR_OK: int = 0
ERROR_NODE_CAPACITY: int = 1
ERROR_EDGE_CAPACITY: int = 2
ERROR_PAYLOAD_CAPACITY: int = 3
ERROR_INVALID_REF: int = 4
ERROR_INVALID_TAG: int = 5
ERROR_TYPE_MISMATCH: int = 6
ERROR_INT_OVERFLOW: int = 7
ERROR_CONSTANT_WRITE: int = 8
ERROR_INDEX_OUT_OF_BOUNDS: int = 9
ERROR_KEY_NOT_FOUND: int = 10
ERROR_STACK_OVERFLOW: int = 11
ERROR_UNHASHABLE_KEY: int = 12
ERROR_NON_FINITE_FLOAT: int = 13
ERROR_INVALID_UTF8: int = 14

ERROR_NAMES: Mapping[int, str] = {
    ERROR_OK: "OK",
    ERROR_NODE_CAPACITY: "NODE_CAPACITY",
    ERROR_EDGE_CAPACITY: "EDGE_CAPACITY",
    ERROR_PAYLOAD_CAPACITY: "PAYLOAD_CAPACITY",
    ERROR_INVALID_REF: "INVALID_REF",
    ERROR_INVALID_TAG: "INVALID_TAG",
    ERROR_TYPE_MISMATCH: "TYPE_MISMATCH",
    ERROR_INT_OVERFLOW: "INT_OVERFLOW",
    ERROR_CONSTANT_WRITE: "CONSTANT_WRITE",
    ERROR_INDEX_OUT_OF_BOUNDS: "INDEX_OUT_OF_BOUNDS",
    ERROR_KEY_NOT_FOUND: "KEY_NOT_FOUND",
    ERROR_STACK_OVERFLOW: "STACK_OVERFLOW",
    ERROR_UNHASHABLE_KEY: "UNHASHABLE_KEY",
    ERROR_NON_FINITE_FLOAT: "NON_FINITE_FLOAT",
    ERROR_INVALID_UTF8: "INVALID_UTF8",
}

# ABI constants
NODE_STRIDE: int = 4
EDGE_STRIDE: int = 2
COUNTS_STRIDE: int = 3


def abi_fingerprint() -> str:
    """Return a deterministic SHA-256 fingerprint of the VM Heap ABI and source."""
    src = emit_vm_heap_source()
    h = hashlib.sha256()
    h.update(b"duel_vm_heap_abi_v1:")
    h.update(f"tags={sorted(VALID_TAGS)}:".encode("ascii"))
    h.update(f"errors={sorted(ERROR_NAMES.keys())}:".encode("ascii"))
    h.update(src.encode("utf-8"))
    return h.hexdigest()


def emit_vm_heap_source() -> str:
    """Return self-contained CUDA C++ namespace duel_vm_heap header source code.

    The returned source requires no external standard library headers (<stdio.h>,
    <stdlib.h>, <string.h>, <math.h>). It uses only fundamental C/C++ types
    (int, long long, unsigned char, double) and NVRTC built-in keywords.
    """
    return r"""/* duel_vm_heap.cuh - Self-contained CUDA device mutable graph heap primitives.
 * Generated by emit_vm_heap_source(). Do not edit directly if embedded.
 */
#ifndef DUEL_VM_HEAP_CUH
#define DUEL_VM_HEAP_CUH

namespace duel_vm_heap {

// Schema Node Tags (matching schema.py)
enum Tag {
    TAG_NONE = 0,
    TAG_BOOL = 1,
    TAG_INT = 2,
    TAG_FLOAT = 3,
    TAG_STR = 4,
    TAG_LIST = 5,
    TAG_TUPLE = 6,
    TAG_DICT = 7,
    TAG_PLAYER_ENTITY = 8,
    TAG_CHARACTER_ENTITY = 9,
    TAG_CARD_ENTITY = 10
};

// VM Error Status Codes
enum ErrorCode {
    ERROR_OK = 0,
    ERROR_NODE_CAPACITY = 1,
    ERROR_EDGE_CAPACITY = 2,
    ERROR_PAYLOAD_CAPACITY = 3,
    ERROR_INVALID_REF = 4,
    ERROR_INVALID_TAG = 5,
    ERROR_TYPE_MISMATCH = 6,
    ERROR_INT_OVERFLOW = 7,
    ERROR_CONSTANT_WRITE = 8,
    ERROR_INDEX_OUT_OF_BOUNDS = 9,
    ERROR_KEY_NOT_FOUND = 10,
    ERROR_STACK_OVERFLOW = 11,
    ERROR_UNHASHABLE_KEY = 12,
    ERROR_NON_FINITE_FLOAT = 13,
    ERROR_INVALID_UTF8 = 14
};

#ifndef DUEL_VM_STACK_LIMIT
#define DUEL_VM_STACK_LIMIT 256
#endif

#ifndef DUEL_VM_MEMO_LIMIT
#define DUEL_VM_MEMO_LIMIT 512
#endif

// Heap ABI structure (per-game independent context, no global mutable state)
struct Heap {
    int* nodes;
    int* edges;
    unsigned char* payload;
    int* counts;
    int max_nodes, max_edges, max_payload;
    const int* constant_nodes;
    const int* constant_edges;
    const unsigned char* constant_payload;
    int constant_node_count, constant_edge_count, constant_payload_count;
    int error;
};

// Internal node view
struct NodeView {
    int tag;
    int offset;
    int count;
    int extra;
    int is_constant;
};

// Memo entry for deep_clone alias preservation
struct MemoEntry {
    int old_ref;
    int new_ref;
};

// Standalone memory and math primitives (zero external header dependencies)
__device__ inline void vm_memcpy(void* dest, const void* src, int n) {
    unsigned char* d = (unsigned char*)dest;
    const unsigned char* s = (const unsigned char*)src;
    for (int i = 0; i < n; i++) {
        d[i] = s[i];
    }
}

__device__ inline int vm_memcmp(const void* s1, const void* s2, int n) {
    const unsigned char* p1 = (const unsigned char*)s1;
    const unsigned char* p2 = (const unsigned char*)s2;
    for (int i = 0; i < n; i++) {
        if (p1[i] != p2[i]) {
            return (int)p1[i] - (int)p2[i];
        }
    }
    return 0;
}

__device__ inline bool vm_isfinite(double val) {
    unsigned long long u = *(const unsigned long long*)&val;
    unsigned int exp = (unsigned int)((u >> 52) & 0x7FFULL);
    return exp != 0x7FFU;
}

__device__ inline bool vm_isnan(double val) {
    unsigned long long u = *(const unsigned long long*)&val;
    unsigned int exp = (unsigned int)((u >> 52) & 0x7FFULL);
    unsigned long long mantissa = u & 0x000FFFFFFFFFFFFFULL;
    return (exp == 0x7FFU) && (mantissa != 0ULL);
}

// Strict UTF-8 validation and Unicode character (codepoint) counter
__device__ inline int utf8_char_length(const unsigned char* s, int byte_len, int* out_err) {
    int chars = 0;
    int i = 0;
    while (i < byte_len) {
        unsigned char c = s[i];
        if (c < 0x80) {
            chars++;
            i++;
        } else if ((c & 0xE0) == 0xC0) {
            // 2-byte sequence
            if (c < 0xC2 || i + 1 >= byte_len) { *out_err = 1; return -1; }
            if ((s[i + 1] & 0xC0) != 0x80) { *out_err = 1; return -1; }
            chars++;
            i += 2;
        } else if ((c & 0xF0) == 0xE0) {
            // 3-byte sequence
            if (i + 2 >= byte_len) { *out_err = 1; return -1; }
            unsigned char c2 = s[i + 1];
            unsigned char c3 = s[i + 2];
            if ((c2 & 0xC0) != 0x80 || (c3 & 0xC0) != 0x80) { *out_err = 1; return -1; }
            if (c == 0xE0 && c2 < 0xA0) { *out_err = 1; return -1; } // overlong
            if (c == 0xED && c2 >= 0xA0) { *out_err = 1; return -1; } // surrogates 0xD800..0xDFFF
            chars++;
            i += 3;
        } else if ((c & 0xF8) == 0xF0) {
            // 4-byte sequence
            if (i + 3 >= byte_len) { *out_err = 1; return -1; }
            unsigned char c2 = s[i + 1];
            unsigned char c3 = s[i + 2];
            unsigned char c4 = s[i + 3];
            if ((c2 & 0xC0) != 0x80 || (c3 & 0xC0) != 0x80 || (c4 & 0xC0) != 0x80) { *out_err = 1; return -1; }
            if (c == 0xF0 && c2 < 0x90) { *out_err = 1; return -1; } // overlong
            if (c == 0xF4 && c2 > 0x8F) { *out_err = 1; return -1; } // > 0x10FFFF
            if (c > 0xF4) { *out_err = 1; return -1; }
            chars++;
            i += 4;
        } else {
            *out_err = 1;
            return -1;
        }
    }
    *out_err = 0;
    return chars;
}

// Initialize per-game independent Heap context
__device__ inline void init_heap(
    Heap* heap,
    int* nodes,
    int* edges,
    unsigned char* payload,
    int* counts,
    int max_nodes,
    int max_edges,
    int max_payload,
    const int* constant_nodes,
    const int* constant_edges,
    const unsigned char* constant_payload,
    int constant_node_count,
    int constant_edge_count,
    int constant_payload_count
) {
    heap->nodes = nodes;
    heap->edges = edges;
    heap->payload = payload;
    heap->counts = counts;
    heap->max_nodes = max_nodes;
    heap->max_edges = max_edges;
    heap->max_payload = max_payload;
    heap->constant_nodes = constant_nodes;
    heap->constant_edges = constant_edges;
    heap->constant_payload = constant_payload;
    heap->constant_node_count = constant_node_count;
    heap->constant_edge_count = constant_edge_count;
    heap->constant_payload_count = constant_payload_count;
    heap->error = ERROR_OK;
}

// Internal node resolution (positive: mutable state; negative: constant program graph)
__device__ inline int get_node(const Heap* heap, int ref, NodeView* out_node) {
    if (ref >= 0) {
        if (ref >= heap->counts[0]) {
            return 0;
        }
        out_node->tag = heap->nodes[ref * 4 + 0];
        out_node->offset = heap->nodes[ref * 4 + 1];
        out_node->count = heap->nodes[ref * 4 + 2];
        out_node->extra = heap->nodes[ref * 4 + 3];
        out_node->is_constant = 0;
        return 1;
    } else {
        int const_idx = -1 - ref;
        if (const_idx < 0 || const_idx >= heap->constant_node_count) {
            return 0;
        }
        out_node->tag = heap->constant_nodes[const_idx * 4 + 0];
        out_node->offset = heap->constant_nodes[const_idx * 4 + 1];
        out_node->count = heap->constant_nodes[const_idx * 4 + 2];
        out_node->extra = heap->constant_nodes[const_idx * 4 + 3];
        out_node->is_constant = 1;
        return 1;
    }
}

__device__ inline int get_edge(const Heap* heap, const NodeView* node, int idx, int* out_k, int* out_v) {
    if (idx < 0 || idx >= node->count) return 0;
    int edge_idx = node->offset + idx;
    if (node->is_constant) {
        if (edge_idx < 0 || edge_idx >= heap->constant_edge_count) return 0;
        *out_k = heap->constant_edges[edge_idx * 2 + 0];
        *out_v = heap->constant_edges[edge_idx * 2 + 1];
    } else {
        if (edge_idx < 0 || edge_idx >= heap->counts[1]) return 0;
        *out_k = heap->edges[edge_idx * 2 + 0];
        *out_v = heap->edges[edge_idx * 2 + 1];
    }
    return 1;
}

__device__ inline const unsigned char* get_payload_ptr(const Heap* heap, const NodeView* node) {
    if (node->is_constant) {
        if (node->offset < 0 || node->offset + node->count > heap->constant_payload_count) return 0;
        return heap->constant_payload + node->offset;
    } else {
        if (node->offset < 0 || node->offset + node->count > heap->counts[2]) return 0;
        return heap->payload + node->offset;
    }
}

// 1. tag: returns tag (0..10) or -1 on error
__device__ inline int tag(Heap* heap, int ref) {
    if (heap->error != ERROR_OK) return -1;
    NodeView node;
    if (!get_node(heap, ref, &node)) {
        heap->error = ERROR_INVALID_REF;
        return -1;
    }
    if (node.tag < 0 || node.tag > TAG_CARD_ENTITY) {
        heap->error = ERROR_INVALID_TAG;
        return -1;
    }
    return node.tag;
}

// 2. make_none: creates TAG_NONE node
__device__ inline int make_none(Heap* heap) {
    if (heap->error != ERROR_OK) return -1;
    if (heap->counts[0] + 1 > heap->max_nodes) {
        heap->error = ERROR_NODE_CAPACITY;
        return -1;
    }
    int ref = heap->counts[0]++;
    heap->nodes[ref * 4 + 0] = TAG_NONE;
    heap->nodes[ref * 4 + 1] = 0;
    heap->nodes[ref * 4 + 2] = 0;
    heap->nodes[ref * 4 + 3] = 0;
    return ref;
}

// 3. make_bool: creates TAG_BOOL node
__device__ inline int make_bool(Heap* heap, int val) {
    if (heap->error != ERROR_OK) return -1;
    if (heap->counts[0] + 1 > heap->max_nodes) {
        heap->error = ERROR_NODE_CAPACITY;
        return -1;
    }
    int ref = heap->counts[0]++;
    heap->nodes[ref * 4 + 0] = TAG_BOOL;
    heap->nodes[ref * 4 + 1] = 0;
    heap->nodes[ref * 4 + 2] = 0;
    heap->nodes[ref * 4 + 3] = (val ? 1 : 0);
    return ref;
}

// 4. make_int64: encodes signed 64-bit integer into minimal signed bytes (little-endian)
__device__ inline int make_int64(Heap* heap, long long val) {
    if (heap->error != ERROR_OK) return -1;
    unsigned char raw[8];
    unsigned long long u = (unsigned long long)val;
    for (int i = 0; i < 8; i++) {
        raw[i] = (unsigned char)((u >> (i * 8)) & 0xFF);
    }
    int len = 8;
    while (len > 1) {
        unsigned char top = raw[len - 1];
        unsigned char prev = raw[len - 2];
        if (top == 0x00 && ((prev & 0x80) == 0)) {
            len--;
        } else if (top == 0xFF && ((prev & 0x80) != 0)) {
            len--;
        } else {
            break;
        }
    }
    if (heap->counts[2] + len > heap->max_payload) {
        heap->error = ERROR_PAYLOAD_CAPACITY;
        return -1;
    }
    if (heap->counts[0] + 1 > heap->max_nodes) {
        heap->error = ERROR_NODE_CAPACITY;
        return -1;
    }
    int offset = heap->counts[2];
    for (int i = 0; i < len; i++) {
        heap->payload[offset + i] = raw[i];
    }
    heap->counts[2] += len;
    int ref = heap->counts[0]++;
    heap->nodes[ref * 4 + 0] = TAG_INT;
    heap->nodes[ref * 4 + 1] = offset;
    heap->nodes[ref * 4 + 2] = len;
    heap->nodes[ref * 4 + 3] = 0;
    return ref;
}

// 5. read_int64: reads integer. If > 64 bits, explicitly flags ERROR_INT_OVERFLOW
__device__ inline int read_int64(Heap* heap, int ref, long long* out_val) {
    if (heap->error != ERROR_OK) return -1;
    NodeView node;
    if (!get_node(heap, ref, &node)) {
        heap->error = ERROR_INVALID_REF;
        return -1;
    }
    if (node.tag != TAG_INT) {
        heap->error = ERROR_TYPE_MISMATCH;
        return -1;
    }
    if (node.count < 1) {
        heap->error = ERROR_INVALID_REF;
        return -1;
    }
    const unsigned char* p = get_payload_ptr(heap, &node);
    if (!p) {
        heap->error = ERROR_INVALID_REF;
        return -1;
    }
    // Frozen arbitrary-precision payloads can contain redundant sign bytes.
    // Validate the mathematical signed range, rather than rejecting int64 min
    // solely because its source serialization used nine bytes.
    int width=node.count<8?node.count:8;
    unsigned char sign=(p[width-1]&0x80)?0xFF:0;
    for(int i=8;i<node.count;i++)if(p[i]!=sign){heap->error=ERROR_INT_OVERFLOW;return -1;}
    unsigned long long u = 0;
    for (int i = 0; i < width; i++) {
        u |= ((unsigned long long)p[i]) << (i * 8);
    }
    if (sign) {
        if (width < 8) {
            unsigned long long mask = (~0ULL) << (width * 8);
            u |= mask;
        }
    }
    *out_val = (long long)u;
    return 0;
}

// 6. make_float64: encodes finite double into 8 little-endian bytes
__device__ inline int make_float64(Heap* heap, double val) {
    if (heap->error != ERROR_OK) return -1;
    if (!vm_isfinite(val)) {
        heap->error = ERROR_NON_FINITE_FLOAT;
        return -1;
    }
    if (heap->counts[2] + 8 > heap->max_payload) {
        heap->error = ERROR_PAYLOAD_CAPACITY;
        return -1;
    }
    if (heap->counts[0] + 1 > heap->max_nodes) {
        heap->error = ERROR_NODE_CAPACITY;
        return -1;
    }
    int offset = heap->counts[2];
    unsigned long long u = *(const unsigned long long*)&val;
    for (int i = 0; i < 8; i++) {
        heap->payload[offset + i] = (unsigned char)((u >> (i * 8)) & 0xFF);
    }
    heap->counts[2] += 8;
    int ref = heap->counts[0]++;
    heap->nodes[ref * 4 + 0] = TAG_FLOAT;
    heap->nodes[ref * 4 + 1] = offset;
    heap->nodes[ref * 4 + 2] = 8;
    heap->nodes[ref * 4 + 3] = 0;
    return ref;
}

// 7. read_float64: reads finite double from TAG_FLOAT node
__device__ inline int read_float64(Heap* heap, int ref, double* out_val) {
    if (heap->error != ERROR_OK) return -1;
    NodeView node;
    if (!get_node(heap, ref, &node)) {
        heap->error = ERROR_INVALID_REF;
        return -1;
    }
    if (node.tag != TAG_FLOAT) {
        heap->error = ERROR_TYPE_MISMATCH;
        return -1;
    }
    if (node.count != 8) {
        heap->error = ERROR_INVALID_REF;
        return -1;
    }
    const unsigned char* p = get_payload_ptr(heap, &node);
    if (!p) {
        heap->error = ERROR_INVALID_REF;
        return -1;
    }
    unsigned long long u = 0;
    for (int i = 0; i < 8; i++) {
        u |= ((unsigned long long)p[i]) << (i * 8);
    }
    double d = *(const double*)&u;
    if (!vm_isfinite(d)) {
        heap->error = ERROR_NON_FINITE_FLOAT;
        return -1;
    }
    *out_val = d;
    return 0;
}

// 8. make_utf8: creates TAG_STR node with UTF-8 payload validation
__device__ inline int make_utf8(Heap* heap, const char* str, int byte_len) {
    if (heap->error != ERROR_OK) return -1;
    if (byte_len < 0) {
        heap->error = ERROR_INVALID_UTF8;
        return -1;
    }
    int err = 0;
    utf8_char_length((const unsigned char*)str, byte_len, &err);
    if (err) {
        heap->error = ERROR_INVALID_UTF8;
        return -1;
    }
    if (heap->counts[2] + byte_len > heap->max_payload) {
        heap->error = ERROR_PAYLOAD_CAPACITY;
        return -1;
    }
    if (heap->counts[0] + 1 > heap->max_nodes) {
        heap->error = ERROR_NODE_CAPACITY;
        return -1;
    }
    int offset = heap->counts[2];
    for (int i = 0; i < byte_len; i++) {
        heap->payload[offset + i] = (unsigned char)str[i];
    }
    heap->counts[2] += byte_len;
    int ref = heap->counts[0]++;
    heap->nodes[ref * 4 + 0] = TAG_STR;
    heap->nodes[ref * 4 + 1] = offset;
    heap->nodes[ref * 4 + 2] = byte_len;
    heap->nodes[ref * 4 + 3] = 0;
    return ref;
}

// 9. str_char_length: returns real Unicode codepoint count (not byte count)
__device__ inline int str_char_length(Heap* heap, int ref) {
    if (heap->error != ERROR_OK) return -1;
    NodeView node;
    if (!get_node(heap, ref, &node)) {
        heap->error = ERROR_INVALID_REF;
        return -1;
    }
    if (node.tag != TAG_STR) {
        heap->error = ERROR_TYPE_MISMATCH;
        return -1;
    }
    const unsigned char* p = get_payload_ptr(heap, &node);
    if (!p && node.count > 0) {
        heap->error = ERROR_INVALID_REF;
        return -1;
    }
    int err = 0;
    int chars = utf8_char_length(p, node.count, &err);
    if (err) {
        heap->error = ERROR_INVALID_UTF8;
        return -1;
    }
    return chars;
}

// 10. str_compare: lexicographical UTF-8 codepoint comparison
__device__ inline int str_compare(Heap* heap, int ref_a, int ref_b) {
    if (heap->error != ERROR_OK) return 0;
    NodeView na, nb;
    if (!get_node(heap, ref_a, &na) || !get_node(heap, ref_b, &nb)) {
        heap->error = ERROR_INVALID_REF;
        return 0;
    }
    if (na.tag != TAG_STR || nb.tag != TAG_STR) {
        heap->error = ERROR_TYPE_MISMATCH;
        return 0;
    }
    const unsigned char* pa = get_payload_ptr(heap, &na);
    const unsigned char* pb = get_payload_ptr(heap, &nb);
    int min_len = (na.count < nb.count) ? na.count : nb.count;
    for (int i = 0; i < min_len; i++) {
        if (pa[i] != pb[i]) {
            return ((int)pa[i] - (int)pb[i]);
        }
    }
    return na.count - nb.count;
}

// 11. truth: Python-like truthiness evaluation
__device__ inline int truth(Heap* heap, int ref) {
    if (heap->error != ERROR_OK) return -1;
    NodeView node;
    if (!get_node(heap, ref, &node)) {
        heap->error = ERROR_INVALID_REF;
        return -1;
    }
    switch (node.tag) {
        case TAG_NONE:
            return 0;
        case TAG_BOOL:
            return (node.extra != 0) ? 1 : 0;
        case TAG_INT: {
            const unsigned char* p = get_payload_ptr(heap, &node);
            if (!p) { heap->error = ERROR_INVALID_REF; return -1; }
            for (int i = 0; i < node.count; i++) {
                if (p[i] != 0) return 1;
            }
            return 0;
        }
        case TAG_FLOAT: {
            double d = 0.0;
            if (read_float64(heap, ref, &d) != 0) return -1;
            return (d != 0.0) ? 1 : 0;
        }
        case TAG_STR:
            return (node.count > 0) ? 1 : 0;
        case TAG_LIST:
        case TAG_TUPLE:
        case TAG_DICT:
        case TAG_PLAYER_ENTITY:
        case TAG_CHARACTER_ENTITY:
        case TAG_CARD_ENTITY:
            return (node.count > 0) ? 1 : 0;
        default:
            heap->error = ERROR_INVALID_TAG;
            return -1;
    }
}

// 12. key_equal: Dict key equality with Python semantics across None/bool/int/float/str/tuple
__device__ inline int key_equal(Heap* heap, int ref_a, int ref_b);

// Compare arbitrary-precision signed bytes against an exact finite binary64 integer.
// No cast at the int64 boundary, and no precision-losing integer-to-double coercion.
__device__ inline int integer_equals_double(Heap* heap,int ref,double floating){
 NodeView n;if(!get_node(heap,ref,&n)||n.tag!=TAG_INT||n.count<1){heap->error=ERROR_INVALID_REF;return 0;}
 const unsigned char* bytes=get_payload_ptr(heap,&n);if(!bytes){heap->error=ERROR_INVALID_REF;return 0;}
 union Bits{double d;unsigned long long u;} bits;bits.d=floating;
 unsigned long long absolute=bits.u&0x7FFFFFFFFFFFFFFFULL;
 if(!absolute){for(int i=0;i<n.count;i++)if(bytes[i])return 0;return 1;}
 int exponent=(int)(absolute>>52)-1023;if(exponent<0||exponent>1023)return 0;
 unsigned long long mantissa=(absolute&0xFFFFFFFFFFFFFULL)|0x10000000000000ULL;
 int shift=exponent-52;
 if(shift<0){int right=-shift;unsigned long long mask=(1ULL<<right)-1;if(mantissa&mask)return 0;mantissa>>=right;shift=0;}
 int negative=(int)(bits.u>>63),extension=bytes[n.count-1]&0x80?255:0;
 int width=exponent/8+2;if(width<n.count)width=n.count;unsigned int carry=negative?1:0;
 for(int i=0;i<width;i++){
  long long offset=(long long)i*8-shift;unsigned int magnitude=0;
  if(offset>=0&&offset<64)magnitude=(unsigned int)((mantissa>>offset)&255ULL);
  else if(offset<0&&offset> -8)magnitude=(unsigned int)((mantissa<<(-offset))&255ULL);
  unsigned int expected=magnitude;
  if(negative){expected=(255U-magnitude)+carry;carry=expected>>8;expected&=255U;}
  unsigned int actual=i<n.count?bytes[i]:(unsigned int)extension;
  if(actual!=expected)return 0;
 }return 1;
}

__device__ inline int key_equal_internal(Heap* heap, int ref_a, int ref_b, int depth) {
    if (heap->error != ERROR_OK) return 0;
    if (depth > 32) {
        heap->error = ERROR_STACK_OVERFLOW;
        return 0;
    }
    NodeView na, nb;
    if (!get_node(heap, ref_a, &na) || !get_node(heap, ref_b, &nb)) {
        heap->error = ERROR_INVALID_REF;
        return 0;
    }
    // Check hashability: reject lists, dicts, entities, and unknown tags
    if (na.tag == TAG_LIST || na.tag == TAG_DICT ||
        na.tag == TAG_PLAYER_ENTITY || na.tag == TAG_CHARACTER_ENTITY || na.tag == TAG_CARD_ENTITY ||
        na.tag < 0 || na.tag > TAG_CARD_ENTITY) {
        heap->error = ERROR_UNHASHABLE_KEY;
        return 0;
    }
    if (nb.tag == TAG_LIST || nb.tag == TAG_DICT ||
        nb.tag == TAG_PLAYER_ENTITY || nb.tag == TAG_CHARACTER_ENTITY || nb.tag == TAG_CARD_ENTITY ||
        nb.tag < 0 || nb.tag > TAG_CARD_ENTITY) {
        heap->error = ERROR_UNHASHABLE_KEY;
        return 0;
    }

    // 1. None
    if (na.tag == TAG_NONE || nb.tag == TAG_NONE) {
        return (na.tag == TAG_NONE && nb.tag == TAG_NONE) ? 1 : 0;
    }

    // 2. String
    if (na.tag == TAG_STR || nb.tag == TAG_STR) {
        if (na.tag != TAG_STR || nb.tag != TAG_STR) return 0;
        if (na.count != nb.count) return 0;
        const unsigned char* pa = get_payload_ptr(heap, &na);
        const unsigned char* pb = get_payload_ptr(heap, &nb);
        return (vm_memcmp(pa, pb, na.count) == 0) ? 1 : 0;
    }

    // 3. Tuple
    if (na.tag == TAG_TUPLE || nb.tag == TAG_TUPLE) {
        if (na.tag != TAG_TUPLE || nb.tag != TAG_TUPLE) return 0;
        if (na.count != nb.count) return 0;
        for (int i = 0; i < na.count; i++) {
            int ca = 0, va = 0, cb = 0, vb = 0;
            if (!get_edge(heap, &na, i, &ca, &va) || !get_edge(heap, &nb, i, &cb, &vb)) {
                heap->error = ERROR_INVALID_REF;
                return 0;
            }
            int eq = key_equal_internal(heap, ca, cb, depth + 1);
            if (heap->error != ERROR_OK) return 0;
            if (!eq) return 0;
        }
        return 1;
    }

    // 4. Numbers: bool, int, float cross-comparison (Python numeric equality)
    // Extract bool / int64 / float values
    bool is_num_a = (na.tag == TAG_BOOL || na.tag == TAG_INT || na.tag == TAG_FLOAT);
    bool is_num_b = (nb.tag == TAG_BOOL || nb.tag == TAG_INT || nb.tag == TAG_FLOAT);
    if (!is_num_a || !is_num_b) return 0;

    // Both bool
    if (na.tag == TAG_BOOL && nb.tag == TAG_BOOL) {
        return (na.extra == nb.extra) ? 1 : 0;
    }

    // Both float
    if (na.tag == TAG_FLOAT && nb.tag == TAG_FLOAT) {
        double fa = 0.0, fb = 0.0;
        if (read_float64(heap, ref_a, &fa) != 0 || read_float64(heap, ref_b, &fb) != 0) return 0;
        if (vm_isnan(fa) || vm_isnan(fb)) return 0;
        return (fa == fb) ? 1 : 0;
    }

    // Both integers: compare normalized signed bytes, including arbitrary precision.
    if(na.tag==TAG_INT&&nb.tag==TAG_INT){
        const unsigned char* a=get_payload_ptr(heap,&na),*b=get_payload_ptr(heap,&nb);
        if(!a||!b||na.count<1||nb.count<1){heap->error=ERROR_INVALID_REF;return 0;}
        int ac=na.count,bc=nb.count;
        while(ac>1&&((a[ac-1]==0&&!(a[ac-2]&128))||(a[ac-1]==255&&(a[ac-2]&128))))ac--;
        while(bc>1&&((b[bc-1]==0&&!(b[bc-2]&128))||(b[bc-1]==255&&(b[bc-2]&128))))bc--;
        return ac==bc&&vm_memcmp(a,b,ac)==0;
    }
    if(na.tag==TAG_BOOL&&nb.tag==TAG_INT)return integer_equals_double(heap,ref_b,(double)na.extra);
    if(na.tag==TAG_INT&&nb.tag==TAG_BOOL)return integer_equals_double(heap,ref_a,(double)nb.extra);

    // Mixed: bool and float
    if (na.tag == TAG_BOOL && nb.tag == TAG_FLOAT) {
        double fb = 0.0;
        if (read_float64(heap, ref_b, &fb) != 0) return 0;
        return ((double)na.extra == fb) ? 1 : 0;
    }
    if (na.tag == TAG_FLOAT && nb.tag == TAG_BOOL) {
        double fa = 0.0;
        if (read_float64(heap, ref_a, &fa) != 0) return 0;
        return (fa == (double)nb.extra) ? 1 : 0;
    }

    if(na.tag==TAG_INT&&nb.tag==TAG_FLOAT){double f=0;if(read_float64(heap,ref_b,&f)!=0)return 0;return integer_equals_double(heap,ref_a,f);}
    if(na.tag==TAG_FLOAT&&nb.tag==TAG_INT){double f=0;if(read_float64(heap,ref_a,&f)!=0)return 0;return integer_equals_double(heap,ref_b,f);}

    return 0;
}

__device__ inline int key_equal(Heap* heap, int ref_a, int ref_b) {
    return key_equal_internal(heap, ref_a, ref_b, 0);
}

// 13. dict_find: returns entry index 0..count-1 if found, or -1 if not found
__device__ inline int dict_find(Heap* heap, int dict_ref, int key_ref) {
    if (heap->error != ERROR_OK) return -1;
    NodeView node;
    if (!get_node(heap, dict_ref, &node)) {
        heap->error = ERROR_INVALID_REF;
        return -1;
    }
    if (node.tag != TAG_DICT && node.tag != TAG_PLAYER_ENTITY &&
        node.tag != TAG_CHARACTER_ENTITY && node.tag != TAG_CARD_ENTITY) {
        heap->error = ERROR_TYPE_MISMATCH;
        return -1;
    }
    for (int i = 0; i < node.count; i++) {
        int k = 0, v = 0;
        if (!get_edge(heap, &node, i, &k, &v)) {
            heap->error = ERROR_INVALID_REF;
            return -1;
        }
        int eq = key_equal(heap, k, key_ref);
        if (heap->error != ERROR_OK) return -1;
        if (eq) return i;
    }
    return -1;
}

// 14. dict_get: returns val_ref if key found, or default_ref if missing
__device__ inline int dict_get(Heap* heap, int dict_ref, int key_ref, int default_ref) {
    if (heap->error != ERROR_OK) return -1;
    int idx = dict_find(heap, dict_ref, key_ref);
    if (heap->error != ERROR_OK) return -1;
    if (idx < 0) return default_ref;
    NodeView node;
    get_node(heap, dict_ref, &node);
    int k = 0, v = 0;
    get_edge(heap, &node, idx, &k, &v);
    return v;
}

// 15. dict_set: sets or updates key in dictionary, preserving insertion order
__device__ inline int dict_set(Heap* heap, int dict_ref, int key_ref, int val_ref) {
    if (heap->error != ERROR_OK) return -1;
    if (dict_ref < 0) {
        heap->error = ERROR_CONSTANT_WRITE;
        return -1;
    }
    NodeView node;
    if (!get_node(heap, dict_ref, &node)) {
        heap->error = ERROR_INVALID_REF;
        return -1;
    }
    if (node.tag != TAG_DICT && node.tag != TAG_PLAYER_ENTITY &&
        node.tag != TAG_CHARACTER_ENTITY && node.tag != TAG_CARD_ENTITY) {
        heap->error = ERROR_TYPE_MISMATCH;
        return -1;
    }
    // Verify key hashability
    key_equal(heap, key_ref, key_ref);
    if (heap->error != ERROR_OK) return -1;

    int idx = dict_find(heap, dict_ref, key_ref);
    if (heap->error != ERROR_OK) return -1;

    if (idx >= 0) {
        // Update existing entry value in-place
        heap->edges[(node.offset + idx) * 2 + 1] = val_ref;
        return 0;
    }

    // New entry: append to edge list
    if (node.offset + node.count == heap->counts[1]) {
        // Dict is at end of edge storage; extend in-place if capacity permits
        if (heap->counts[1] + 1 > heap->max_edges) {
            heap->error = ERROR_EDGE_CAPACITY;
            return -1;
        }
        int edge_idx = heap->counts[1]++;
        heap->edges[edge_idx * 2 + 0] = key_ref;
        heap->edges[edge_idx * 2 + 1] = val_ref;
        heap->nodes[dict_ref * 4 + 2] = node.count + 1;
        return 0;
    } else {
        // Dict is not at edge tail; relocate its edge block to tail
        int new_count = node.count + 1;
        if (heap->counts[1] + new_count > heap->max_edges) {
            heap->error = ERROR_EDGE_CAPACITY;
            return -1;
        }
        int new_offset = heap->counts[1];
        for (int i = 0; i < node.count; i++) {
            heap->edges[(new_offset + i) * 2 + 0] = heap->edges[(node.offset + i) * 2 + 0];
            heap->edges[(new_offset + i) * 2 + 1] = heap->edges[(node.offset + i) * 2 + 1];
        }
        heap->edges[(new_offset + node.count) * 2 + 0] = key_ref;
        heap->edges[(new_offset + node.count) * 2 + 1] = val_ref;
        heap->counts[1] += new_count;
        heap->nodes[dict_ref * 4 + 1] = new_offset;
        heap->nodes[dict_ref * 4 + 2] = new_count;
        return 0;
    }
}

// 16. dict_delete: deletes key from dict, maintaining insertion order
__device__ inline int dict_delete(Heap* heap, int dict_ref, int key_ref) {
    if (heap->error != ERROR_OK) return -1;
    if (dict_ref < 0) {
        heap->error = ERROR_CONSTANT_WRITE;
        return -1;
    }
    int idx = dict_find(heap, dict_ref, key_ref);
    if (heap->error != ERROR_OK) return -1;
    if (idx < 0) {
        heap->error = ERROR_KEY_NOT_FOUND;
        return -1;
    }
    NodeView node;
    get_node(heap, dict_ref, &node);
    // Shift subsequent entries down
    for (int i = idx; i < node.count - 1; i++) {
        heap->edges[(node.offset + i) * 2 + 0] = heap->edges[(node.offset + i + 1) * 2 + 0];
        heap->edges[(node.offset + i) * 2 + 1] = heap->edges[(node.offset + i + 1) * 2 + 1];
    }
    heap->nodes[dict_ref * 4 + 2] = node.count - 1;
    if (node.offset + node.count == heap->counts[1]) {
        heap->counts[1]--;
    }
    return 0;
}

// 17. list_get: returns element at index (supports negative indexing)
__device__ inline int list_get(Heap* heap, int list_ref, int index) {
    if (heap->error != ERROR_OK) return -1;
    NodeView node;
    if (!get_node(heap, list_ref, &node)) {
        heap->error = ERROR_INVALID_REF;
        return -1;
    }
    if (node.tag != TAG_LIST && node.tag != TAG_TUPLE) {
        heap->error = ERROR_TYPE_MISMATCH;
        return -1;
    }
    if (index < 0) index = node.count + index;
    if (index < 0 || index >= node.count) {
        heap->error = ERROR_INDEX_OUT_OF_BOUNDS;
        return -1;
    }
    int k = 0, v = 0;
    if (!get_edge(heap, &node, index, &k, &v)) {
        heap->error = ERROR_INVALID_REF;
        return -1;
    }
    return k;
}

// 18. list_set: sets element at index (rejects tuples and constant writes)
__device__ inline int list_set(Heap* heap, int list_ref, int index, int val_ref) {
    if (heap->error != ERROR_OK) return -1;
    if (list_ref < 0) {
        heap->error = ERROR_CONSTANT_WRITE;
        return -1;
    }
    NodeView node;
    if (!get_node(heap, list_ref, &node)) {
        heap->error = ERROR_INVALID_REF;
        return -1;
    }
    if (node.tag != TAG_LIST) {
        heap->error = ERROR_TYPE_MISMATCH;
        return -1;
    }
    if (index < 0) index = node.count + index;
    if (index < 0 || index >= node.count) {
        heap->error = ERROR_INDEX_OUT_OF_BOUNDS;
        return -1;
    }
    heap->edges[(node.offset + index) * 2 + 0] = val_ref;
    return 0;
}

// 19. list_append: appends element to list with edge relocation if needed
__device__ inline int list_append(Heap* heap, int list_ref, int val_ref) {
    if (heap->error != ERROR_OK) return -1;
    if (list_ref < 0) {
        heap->error = ERROR_CONSTANT_WRITE;
        return -1;
    }
    NodeView node;
    if (!get_node(heap, list_ref, &node)) {
        heap->error = ERROR_INVALID_REF;
        return -1;
    }
    if (node.tag != TAG_LIST) {
        heap->error = ERROR_TYPE_MISMATCH;
        return -1;
    }
    if (node.offset + node.count == heap->counts[1]) {
        if (heap->counts[1] + 1 > heap->max_edges) {
            heap->error = ERROR_EDGE_CAPACITY;
            return -1;
        }
        int edge_idx = heap->counts[1]++;
        heap->edges[edge_idx * 2 + 0] = val_ref;
        heap->edges[edge_idx * 2 + 1] = -1;
        heap->nodes[list_ref * 4 + 2] = node.count + 1;
        return 0;
    } else {
        int new_count = node.count + 1;
        if (heap->counts[1] + new_count > heap->max_edges) {
            heap->error = ERROR_EDGE_CAPACITY;
            return -1;
        }
        int new_offset = heap->counts[1];
        for (int i = 0; i < node.count; i++) {
            heap->edges[(new_offset + i) * 2 + 0] = heap->edges[(node.offset + i) * 2 + 0];
            heap->edges[(new_offset + i) * 2 + 1] = -1;
        }
        heap->edges[(new_offset + node.count) * 2 + 0] = val_ref;
        heap->edges[(new_offset + node.count) * 2 + 1] = -1;
        heap->counts[1] += new_count;
        heap->nodes[list_ref * 4 + 1] = new_offset;
        heap->nodes[list_ref * 4 + 2] = new_count;
        return 0;
    }
}

// 20. list_pop: pops last element from list
__device__ inline int list_pop(Heap* heap, int list_ref, int* out_val_ref) {
    if (heap->error != ERROR_OK) return -1;
    if (list_ref < 0) {
        heap->error = ERROR_CONSTANT_WRITE;
        return -1;
    }
    NodeView node;
    if (!get_node(heap, list_ref, &node)) {
        heap->error = ERROR_INVALID_REF;
        return -1;
    }
    if (node.tag != TAG_LIST) {
        heap->error = ERROR_TYPE_MISMATCH;
        return -1;
    }
    if (node.count <= 0) {
        heap->error = ERROR_INDEX_OUT_OF_BOUNDS;
        return -1;
    }
    int last_idx = node.count - 1;
    *out_val_ref = heap->edges[(node.offset + last_idx) * 2 + 0];
    heap->nodes[list_ref * 4 + 2] = last_idx;
    if (node.offset + node.count == heap->counts[1]) {
        heap->counts[1]--;
    }
    return 0;
}

// 21. make_list: creates empty mutable list
__device__ inline int make_list(Heap* heap) {
    if (heap->error != ERROR_OK) return -1;
    if (heap->counts[0] + 1 > heap->max_nodes) {
        heap->error = ERROR_NODE_CAPACITY;
        return -1;
    }
    int ref = heap->counts[0]++;
    heap->nodes[ref * 4 + 0] = TAG_LIST;
    heap->nodes[ref * 4 + 1] = heap->counts[1];
    heap->nodes[ref * 4 + 2] = 0;
    heap->nodes[ref * 4 + 3] = 0;
    return ref;
}

// 22. make_tuple: creates immutable tuple with given child refs
__device__ inline int make_tuple(Heap* heap, const int* child_refs, int count) {
    if (heap->error != ERROR_OK) return -1;
    if (count < 0) {
        heap->error = ERROR_TYPE_MISMATCH;
        return -1;
    }
    if (heap->counts[0] + 1 > heap->max_nodes) {
        heap->error = ERROR_NODE_CAPACITY;
        return -1;
    }
    if (heap->counts[1] + count > heap->max_edges) {
        heap->error = ERROR_EDGE_CAPACITY;
        return -1;
    }
    int start_edge = heap->counts[1];
    for (int i = 0; i < count; i++) {
        heap->edges[(start_edge + i) * 2 + 0] = child_refs[i];
        heap->edges[(start_edge + i) * 2 + 1] = -1;
    }
    heap->counts[1] += count;
    int ref = heap->counts[0]++;
    heap->nodes[ref * 4 + 0] = TAG_TUPLE;
    heap->nodes[ref * 4 + 1] = start_edge;
    heap->nodes[ref * 4 + 2] = count;
    heap->nodes[ref * 4 + 3] = 0;
    return ref;
}

// 23. make_dict: creates empty mutable dict
__device__ inline int make_dict(Heap* heap) {
    if (heap->error != ERROR_OK) return -1;
    if (heap->counts[0] + 1 > heap->max_nodes) {
        heap->error = ERROR_NODE_CAPACITY;
        return -1;
    }
    int ref = heap->counts[0]++;
    heap->nodes[ref * 4 + 0] = TAG_DICT;
    heap->nodes[ref * 4 + 1] = heap->counts[1];
    heap->nodes[ref * 4 + 2] = 0;
    heap->nodes[ref * 4 + 3] = 0;
    return ref;
}

// 24. make_entity: creates empty PlayerEntity/CharacterEntity/CardEntity
__device__ inline int make_entity(Heap* heap, int entity_tag) {
    if (heap->error != ERROR_OK) return -1;
    if (entity_tag != TAG_PLAYER_ENTITY && entity_tag != TAG_CHARACTER_ENTITY &&
        entity_tag != TAG_CARD_ENTITY) {
        heap->error = ERROR_INVALID_TAG;
        return -1;
    }
    if (heap->counts[0] + 1 > heap->max_nodes) {
        heap->error = ERROR_NODE_CAPACITY;
        return -1;
    }
    int ref = heap->counts[0]++;
    heap->nodes[ref * 4 + 0] = entity_tag;
    heap->nodes[ref * 4 + 1] = heap->counts[1];
    heap->nodes[ref * 4 + 2] = 0;
    heap->nodes[ref * 4 + 3] = 0;
    return ref;
}

// Clone single scalar node verbatim into mutable heap
__device__ inline int clone_scalar_node(Heap* heap, const NodeView* node) {
    if (node->tag == TAG_NONE) {
        return make_none(heap);
    } else if (node->tag == TAG_BOOL) {
        return make_bool(heap, node->extra);
    } else if (node->tag == TAG_INT || node->tag == TAG_FLOAT || node->tag == TAG_STR) {
        if (heap->counts[0] + 1 > heap->max_nodes) {
            heap->error = ERROR_NODE_CAPACITY;
            return -1;
        }
        if (heap->counts[2] + node->count > heap->max_payload) {
            heap->error = ERROR_PAYLOAD_CAPACITY;
            return -1;
        }
        const unsigned char* src = get_payload_ptr(heap, node);
        if (!src && node->count > 0) {
            heap->error = ERROR_INVALID_REF;
            return -1;
        }
        int offset = heap->counts[2];
        vm_memcpy(heap->payload + offset, src, node->count);
        heap->counts[2] += node->count;
        int ref = heap->counts[0]++;
        heap->nodes[ref * 4 + 0] = node->tag;
        heap->nodes[ref * 4 + 1] = offset;
        heap->nodes[ref * 4 + 2] = node->count;
        heap->nodes[ref * 4 + 3] = node->extra;
        return ref;
    } else {
        heap->error = ERROR_INVALID_TAG;
        return -1;
    }
}

// 25. deep_clone: Two-phase memoized subgraph clone preserving aliases, Entity tags,
// unknown fields, large RNG integers, and materializing constant containers into mutable refs.
__device__ inline int deep_clone(Heap* heap, int root_ref) {
    if (heap->error != ERROR_OK) return -1;
    NodeView root_node;
    if (!get_node(heap, root_ref, &root_node)) {
        heap->error = ERROR_INVALID_REF;
        return -1;
    }

    // Save initial counts for atomic failure rollback
    int init_node_count = heap->counts[0];
    int init_edge_count = heap->counts[1];
    int init_payload_count = heap->counts[2];

    // Single scalar root fast-path
    if (root_node.tag <= TAG_STR) {
        int res = clone_scalar_node(heap, &root_node);
        if (heap->error != ERROR_OK) {
            heap->counts[0] = init_node_count;
            heap->counts[1] = init_edge_count;
            heap->counts[2] = init_payload_count;
            return -1;
        }
        return res;
    }

    // Fixed memo table and traversal stack on thread local memory
    MemoEntry memo[DUEL_VM_MEMO_LIMIT];
    int memo_count = 0;

    int stack[DUEL_VM_STACK_LIMIT];
    int stack_top = 0;

    stack[stack_top++] = root_ref;

    // === PHASE 1: Discovery, Node Header Allocation, and Memo Mapping ===
    while (stack_top > 0) {
        int curr_ref = stack[--stack_top];

        // Check if curr_ref already memoized
        bool already_seen = false;
        for (int m = 0; m < memo_count; m++) {
            if (memo[m].old_ref == curr_ref) {
                already_seen = true;
                break;
            }
        }
        if (already_seen) continue;

        if (memo_count >= DUEL_VM_MEMO_LIMIT) {
            heap->error = ERROR_STACK_OVERFLOW;
            break;
        }

        NodeView node;
        if (!get_node(heap, curr_ref, &node)) {
            heap->error = ERROR_INVALID_REF;
            break;
        }

        if (node.tag <= TAG_STR) {
            // Scalar node: clone immediately and memoize
            int cloned_scalar = clone_scalar_node(heap, &node);
            if (heap->error != ERROR_OK) break;
            memo[memo_count].old_ref = curr_ref;
            memo[memo_count].new_ref = cloned_scalar;
            memo_count++;
        } else if (node.tag <= TAG_CARD_ENTITY) {
            // Container node: allocate node header and edge slice
            if (heap->counts[0] + 1 > heap->max_nodes) {
                heap->error = ERROR_NODE_CAPACITY;
                break;
            }
            if (heap->counts[1] + node.count > heap->max_edges) {
                heap->error = ERROR_EDGE_CAPACITY;
                break;
            }
            int new_node_ref = heap->counts[0]++;
            int edge_start = heap->counts[1];
            heap->counts[1] += node.count;

            heap->nodes[new_node_ref * 4 + 0] = node.tag;
            heap->nodes[new_node_ref * 4 + 1] = edge_start;
            heap->nodes[new_node_ref * 4 + 2] = node.count;
            heap->nodes[new_node_ref * 4 + 3] = node.extra;

            memo[memo_count].old_ref = curr_ref;
            memo[memo_count].new_ref = new_node_ref;
            memo_count++;

            // Push children onto traversal stack
            for (int i = 0; i < node.count; i++) {
                int k = 0, v = 0;
                if (!get_edge(heap, &node, i, &k, &v)) {
                    heap->error = ERROR_INVALID_REF;
                    break;
                }
                if (node.tag == TAG_LIST || node.tag == TAG_TUPLE) {
                    if (stack_top >= DUEL_VM_STACK_LIMIT) {
                        heap->error = ERROR_STACK_OVERFLOW;
                        break;
                    }
                    stack[stack_top++] = k;
                } else {
                    if (stack_top + 2 > DUEL_VM_STACK_LIMIT) {
                        heap->error = ERROR_STACK_OVERFLOW;
                        break;
                    }
                    stack[stack_top++] = k;
                    stack[stack_top++] = v;
                }
            }
            if (heap->error != ERROR_OK) break;
        } else {
            heap->error = ERROR_INVALID_TAG;
            break;
        }
    }

    if (heap->error != ERROR_OK) {
        heap->counts[0] = init_node_count;
        heap->counts[1] = init_edge_count;
        heap->counts[2] = init_payload_count;
        return -1;
    }

    // === PHASE 2: Reconstruct Edges using Memo Mapping ===
    for (int m = 0; m < memo_count; m++) {
        int old_r = memo[m].old_ref;
        int new_r = memo[m].new_ref;
        NodeView old_n;
        get_node(heap, old_r, &old_n);
        if (old_n.tag > TAG_STR && old_n.tag <= TAG_CARD_ENTITY) {
            int new_edge_offset = heap->nodes[new_r * 4 + 1];
            for (int i = 0; i < old_n.count; i++) {
                int old_k = 0, old_v = 0;
                get_edge(heap, &old_n, i, &old_k, &old_v);

                int new_k = -1;
                for (int j = 0; j < memo_count; j++) {
                    if (memo[j].old_ref == old_k) {
                        new_k = memo[j].new_ref;
                        break;
                    }
                }
                if (new_k < 0) {
                    heap->error = ERROR_INVALID_REF;
                    break;
                }

                if (old_n.tag == TAG_LIST || old_n.tag == TAG_TUPLE) {
                    heap->edges[(new_edge_offset + i) * 2 + 0] = new_k;
                    heap->edges[(new_edge_offset + i) * 2 + 1] = -1;
                } else {
                    int new_v = -1;
                    for (int j = 0; j < memo_count; j++) {
                        if (memo[j].old_ref == old_v) {
                            new_v = memo[j].new_ref;
                            break;
                        }
                    }
                    if (new_v < 0) {
                        heap->error = ERROR_INVALID_REF;
                        break;
                    }
                    heap->edges[(new_edge_offset + i) * 2 + 0] = new_k;
                    heap->edges[(new_edge_offset + i) * 2 + 1] = new_v;
                }
            }
            if (heap->error != ERROR_OK) break;
        }
    }

    if (heap->error != ERROR_OK) {
        heap->counts[0] = init_node_count;
        heap->counts[1] = init_edge_count;
        heap->counts[2] = init_payload_count;
        return -1;
    }

    // Return the new root ref corresponding to root_ref
    for (int m = 0; m < memo_count; m++) {
        if (memo[m].old_ref == root_ref) {
            return memo[m].new_ref;
        }
    }

    heap->error = ERROR_INVALID_REF;
    heap->counts[0] = init_node_count;
    heap->counts[1] = init_edge_count;
    heap->counts[2] = init_payload_count;
    return -1;
}


// Export a heap subgraph into a distinct, empty canonical graph. Dead VM
// allocations are collected; every field reachable from root is retained.
// Work buffers are per-game device allocations, never process-global state.
__device__ inline int compact_index(const Heap* source,int ref) {
    if(ref>=0)return ref<source->counts[0]?ref:-1;
    long long constant=-1LL-ref;
    if(constant<0 || constant>=source->constant_node_count)return -1;
    return source->counts[0]+(int)constant;
}
__device__ inline int compact_enqueue(Heap* source,Heap* target,int ref,int* map,int* queue,int capacity,int* tail) {
    int key=compact_index(source,ref);
    if(key<0){target->error=ERROR_INVALID_REF;return 0;}
    if(map[key]!=-1)return 1;
    if(*tail>=capacity){target->error=ERROR_STACK_OVERFLOW;return 0;}
    map[key]=-2;queue[(*tail)++]=ref;return 1;
}
__device__ inline int compact_into(Heap* source,Heap* target,int root,int* map,int* queue,int capacity) {
    if(source->error || target->error)return -1;
    if(source->nodes==target->nodes || source->edges==target->edges || source->payload==target->payload
       || target->counts[0] || target->counts[1] || target->counts[2]){
        target->error=ERROR_INVALID_REF;return -1;
    }
    long long total=(long long)source->counts[0]+source->constant_node_count;
    if(total<1 || total>capacity){target->error=ERROR_STACK_OVERFLOW;return -1;}
    for(int i=0;i<(int)total;i++)map[i]=-1;
    int head=0,tail=0;
    compact_enqueue(source,target,root,map,queue,capacity,&tail);
    while(head<tail && target->error==ERROR_OK){
        int old=queue[head++];NodeView n;
        if(!get_node(source,old,&n)){target->error=ERROR_INVALID_REF;break;}
        if(n.tag<TAG_NONE || n.tag>TAG_CARD_ENTITY){target->error=ERROR_INVALID_TAG;break;}
        if(target->counts[0]>=target->max_nodes){target->error=ERROR_NODE_CAPACITY;break;}
        int index=target->counts[0]++,offset=0;
        if(n.tag==TAG_INT || n.tag==TAG_FLOAT || n.tag==TAG_STR){
            const unsigned char* bytes=get_payload_ptr(source,&n);
            if((n.count && !bytes) || n.count<0){target->error=ERROR_INVALID_REF;break;}
            if((long long)target->counts[2]+n.count>target->max_payload){target->error=ERROR_PAYLOAD_CAPACITY;break;}
            offset=target->counts[2];vm_memcpy(target->payload+offset,bytes,n.count);target->counts[2]+=n.count;
        }else if(n.tag>=TAG_LIST){
            if(n.count<0 || (long long)target->counts[1]+n.count>target->max_edges){target->error=ERROR_EDGE_CAPACITY;break;}
            offset=target->counts[1];target->counts[1]+=n.count;
            for(int i=0;i<n.count;i++){
                int k=0,v=0;if(!get_edge(source,&n,i,&k,&v)){target->error=ERROR_INVALID_REF;break;}
                if(!compact_enqueue(source,target,k,map,queue,capacity,&tail))break;
                if(n.tag>=TAG_DICT && !compact_enqueue(source,target,v,map,queue,capacity,&tail))break;
            }
        }
        int* out=target->nodes+index*4;out[0]=n.tag;out[1]=offset;out[2]=n.count;out[3]=n.extra;
        map[compact_index(source,old)]=index;
    }
    // Fill child edges only after all aliased references have been assigned.
    for(int j=0;j<tail && target->error==ERROR_OK;j++){
        int old=queue[j];NodeView n;if(!get_node(source,old,&n)){target->error=ERROR_INVALID_REF;break;}
        if(n.tag<TAG_LIST)continue;
        int id=map[compact_index(source,old)],offset=target->nodes[id*4+1];
        for(int i=0;i<n.count;i++){
            int k=0,v=0;if(!get_edge(source,&n,i,&k,&v)){target->error=ERROR_INVALID_REF;break;}
            int ki=compact_index(source,k),vi=n.tag>=TAG_DICT?compact_index(source,v):-1;
            if(ki<0 || map[ki]<0 || (n.tag>=TAG_DICT&&(vi<0||map[vi]<0))){target->error=ERROR_INVALID_REF;break;}
            target->edges[(offset+i)*2]=map[ki];target->edges[(offset+i)*2+1]=n.tag>=TAG_DICT?map[vi]:-1;
        }
    }
    if(target->error){target->counts[0]=target->counts[1]=target->counts[2]=0;return -1;}
    return map[compact_index(source,root)];
}

} // namespace duel_vm_heap

#endif // DUEL_VM_HEAP_CUH
"""
