"""CUDA C++ source emitter for native all/any/sum/min/max reducers on materialized sequences and generators.

Provides:
- SUPPORTED_REDUCER_NAMES: Canonical tuple of directly supported reducers
  ('all', 'any', 'sum', 'min', 'max').
- emit_reducer_source(intrinsic_names: Sequence[str] | tuple[str, ...]) -> str:
  Emits device C++ functions in namespace duel_rule_vm to be inserted immediately
  before call() and return_value().

Scope and Design Contracts:
1. Native Reducer Execution: Directly handles all(), any(), sum(), min(), and max()
   for materialized sequences (list, tuple, dict keys, entity keys, set, frozenset, range,
   and iterators) and generators on device without GPU recursion and without CPU host callbacks.
2. Asynchronous Generator Consumption: Generators are consumed asynchronously via the
   VM execute loop. resume_generator(c, gen, caller, 5, accumulator, MISSING) configures
   frame mode 5 and target=accumulator. When the generator yields or exhausts, the VM's
   return_value intercepts mode 5 and invokes reducer_resume(c, gen, caller, accumulator, item, exhausted).
3. Short-circuiting Semantics: all() and any() short-circuit immediately upon encountering
   a decisive element. For generators, the generator frame remains suspended (status 2)
   so the caller may reuse it later without leaking VM frames.
4. Reducer Accumulator (Tag 39): Stores state across generator yield/exhaustion in heap edges:
   [reducer_code, caller, generator, accumulated_val, has_items, has_default, default_val].
   Created via make_tuple() and retagged to tag 39.
5. Strict Python Parity:
   - sum(): supports optional start (positional or start= keyword, default 0).
   - min()/max(): supports single iterable or multiple positional arguments; default= keyword
     for empty iterables; rejects default= with multiple positional arguments.
   - key= keyword: key callback is not implemented on device and explicitly fails with BAD_CALL
     (never silently ignored).
   - compare: numeric and string ordering via forward-declared compare(c, a, b, mode).
   - reduce_add: forward-declared reduce_add(c, a, b) provided by Main for sum arithmetic.
"""

from __future__ import annotations

from typing import Sequence

SUPPORTED_REDUCER_NAMES: tuple[str, ...] = (
    "all",
    "any",
    "sum",
    "min",
    "max",
)


def emit_reducer_source(intrinsic_names: Sequence[str] | tuple[str, ...] = ()) -> str:
    """Return CUDA C++ source for native reducers in namespace duel_rule_vm.

    Static IDs for reducers are resolved from `intrinsic_names`. Absent reducers
    are assigned distinct negative sentinel IDs (-3001, -3002, ...) so that
    switch/comparison cases never suffer from duplicate value collisions.
    """
    names_tuple = tuple(intrinsic_names)
    injected_ids: dict[str, int] = {}
    for i, name in enumerate(SUPPORTED_REDUCER_NAMES):
        if name in names_tuple:
            injected_ids[name] = names_tuple.index(name)
        else:
            injected_ids[name] = -3001 - i

    return f"""// --- VM Reducers (generated by vm_reducers.py) ---

// Reducer accumulator metadata tag
const int T_REDUCER_ACCUMULATOR = 39;

// Reducer operation codes
enum ReducerCode {{
    REDUCER_ALL = 1,
    REDUCER_ANY = 2,
    REDUCER_SUM = 3,
    REDUCER_MIN = 4,
    REDUCER_MAX = 5
}};

// Static intrinsic IDs (absent IDs receive distinct negative sentinels)
const int NATIVE_ALL = {injected_ids['all']};
const int NATIVE_ANY = {injected_ids['any']};
const int NATIVE_SUM = {injected_ids['sum']};
const int NATIVE_MIN = {injected_ids['min']};
const int NATIVE_MAX = {injected_ids['max']};

// Forward declarations matching primary VM function definitions
__device__ inline int compare(Context* c, int a, int b, int mode);
__device__ inline int reduce_add(Context* c, int a, int b);

// Device UTF-8 string comparison against ASCII literal without host compute
__device__ inline bool reducer_str_equals(Context* c, int str_ref, const char* lit, int lit_len) {{
    if (str_ref == MISSING) return false;
    NodeView nv;
    if (!get_node(&c->h, str_ref, &nv)) return false;
    if (nv.tag != TAG_STR || nv.count != lit_len) return false;
    const unsigned char* p = get_payload_ptr(&c->h, &nv);
    if (!p && lit_len > 0) return false;
    return (vm_memcmp(p, lit, lit_len) == 0);
}}

// Update a field in a Tag 39 accumulator edge list
__device__ inline void reducer_acc_set(Context* c, int acc, int field_idx, int val) {{
    const int* n = node(c, acc);
    if (!n || field_idx < 0 || field_idx >= n[2]) {{
        c->error = BAD_PROGRAM;
        return;
    }}
    long long slot = (long long)n[1] + field_idx;
    if (acc >= 0) {{
        if (slot < 0 || slot >= c->h.counts[1]) {{
            c->error = BAD_PROGRAM;
            return;
        }}
        c->h.edges[slot * 2 + 0] = val;
    }} else {{
        c->error = BAD_PROGRAM;
    }}
}}

// Push output onto caller frame or write to context output if caller is root (-1)
__device__ inline void reducer_push_result(Context* c, int caller, int result) {{
    if (caller < 0) {{
        c->output = result;
    }} else {{
        push(c, frame(c, caller), result);
    }}
}}

// Materialized sequence reducer for all()
__device__ inline int reduce_all_sequence(Context* c, int iter_ref, int caller) {{
    int itag = kind(c, iter_ref);
    if (itag == TAG_LIST || itag == TAG_TUPLE || itag == TAG_DICT ||
        (itag >= 8 && itag <= 10) || itag == 21 || itag == 22) {{
        int cnt = length(c, iter_ref);
        for (int i = 0; i < cnt; i++) {{
            if (++c->steps > c->step_limit) {{ c->error = STEP_LIMIT; return 0; }}
            if (c->deadline && (c->steps & 63) == 0 && clock_ns() >= (unsigned long long)c->deadline) {{ c->error = DEADLINE; return 0; }}
            int item = edge(c, iter_ref, i, 0);
            if (!truth_value(c, item)) {{
                reducer_push_result(c, caller, FALSE_REF);
                return 1;
            }}
        }}
        reducer_push_result(c, caller, TRUE_REF);
        return 1;
    }} else if (itag == T_RANGE_NODE) {{
        long long count = range_size(c, iter_ref);
        if (c->error || c->h.error) return 0;
        long long st = 0, stp = 0;
        if (read_int64(&c->h, edge(c, iter_ref, 0, 0), &st) != 0 ||
            read_int64(&c->h, edge(c, iter_ref, 2, 0), &stp) != 0) {{
            c->error = BAD_CALL; return 0;
        }}
        for (long long i = 0; i < count; i++) {{
            if (++c->steps > c->step_limit) {{ c->error = STEP_LIMIT; return 0; }}
            if (c->deadline && (c->steps & 63) == 0 && clock_ns() >= (unsigned long long)c->deadline) {{ c->error = DEADLINE; return 0; }}
            long long v = (long long)((unsigned long long)st + (unsigned long long)i * (unsigned long long)stp);
            int item = make_int64(&c->h, v);
            if (c->h.error != ERROR_OK) return 0;
            if (!truth_value(c, item)) {{
                reducer_push_result(c, caller, FALSE_REF);
                return 1;
            }}
        }}
        reducer_push_result(c, caller, TRUE_REF);
        return 1;
    }} else if (itag == T_ITER) {{
        while (true) {{
            if (++c->steps > c->step_limit) {{ c->error = STEP_LIMIT; return 0; }}
            if (c->deadline && (c->steps & 63) == 0 && clock_ns() >= (unsigned long long)c->deadline) {{ c->error = DEADLINE; return 0; }}
            int item = iterator_next(c, iter_ref);
            if (item == MISSING) break;
            if (!truth_value(c, item)) {{
                reducer_push_result(c, caller, FALSE_REF);
                return 1;
            }}
        }}
        if (!c->error && !c->h.error) reducer_push_result(c, caller, TRUE_REF);
        return 1;
    }} else {{
        c->error = UNSUPPORTED_TYPE;
        return 0;
    }}
}}

// Materialized sequence reducer for any()
__device__ inline int reduce_any_sequence(Context* c, int iter_ref, int caller) {{
    int itag = kind(c, iter_ref);
    if (itag == TAG_LIST || itag == TAG_TUPLE || itag == TAG_DICT ||
        (itag >= 8 && itag <= 10) || itag == 21 || itag == 22) {{
        int cnt = length(c, iter_ref);
        for (int i = 0; i < cnt; i++) {{
            if (++c->steps > c->step_limit) {{ c->error = STEP_LIMIT; return 0; }}
            if (c->deadline && (c->steps & 63) == 0 && clock_ns() >= (unsigned long long)c->deadline) {{ c->error = DEADLINE; return 0; }}
            int item = edge(c, iter_ref, i, 0);
            if (truth_value(c, item)) {{
                reducer_push_result(c, caller, TRUE_REF);
                return 1;
            }}
        }}
        reducer_push_result(c, caller, FALSE_REF);
        return 1;
    }} else if (itag == T_RANGE_NODE) {{
        long long count = range_size(c, iter_ref);
        if (c->error || c->h.error) return 0;
        long long st = 0, stp = 0;
        if (read_int64(&c->h, edge(c, iter_ref, 0, 0), &st) != 0 ||
            read_int64(&c->h, edge(c, iter_ref, 2, 0), &stp) != 0) {{
            c->error = BAD_CALL; return 0;
        }}
        for (long long i = 0; i < count; i++) {{
            if (++c->steps > c->step_limit) {{ c->error = STEP_LIMIT; return 0; }}
            if (c->deadline && (c->steps & 63) == 0 && clock_ns() >= (unsigned long long)c->deadline) {{ c->error = DEADLINE; return 0; }}
            long long v = (long long)((unsigned long long)st + (unsigned long long)i * (unsigned long long)stp);
            int item = make_int64(&c->h, v);
            if (c->h.error != ERROR_OK) return 0;
            if (truth_value(c, item)) {{
                reducer_push_result(c, caller, TRUE_REF);
                return 1;
            }}
        }}
        reducer_push_result(c, caller, FALSE_REF);
        return 1;
    }} else if (itag == T_ITER) {{
        while (true) {{
            if (++c->steps > c->step_limit) {{ c->error = STEP_LIMIT; return 0; }}
            if (c->deadline && (c->steps & 63) == 0 && clock_ns() >= (unsigned long long)c->deadline) {{ c->error = DEADLINE; return 0; }}
            int item = iterator_next(c, iter_ref);
            if (item == MISSING) break;
            if (truth_value(c, item)) {{
                reducer_push_result(c, caller, TRUE_REF);
                return 1;
            }}
        }}
        if (!c->error && !c->h.error) reducer_push_result(c, caller, FALSE_REF);
        return 1;
    }} else {{
        c->error = UNSUPPORTED_TYPE;
        return 0;
    }}
}}

// Materialized sequence reducer for sum()
__device__ inline int reduce_sum_sequence(Context* c, int iter_ref, int start_val, int caller) {{
    int itag = kind(c, iter_ref);
    int current_sum = start_val;
    if (itag == TAG_LIST || itag == TAG_TUPLE || itag == TAG_DICT ||
        (itag >= 8 && itag <= 10) || itag == 21 || itag == 22) {{
        int cnt = length(c, iter_ref);
        for (int i = 0; i < cnt; i++) {{
            if (++c->steps > c->step_limit) {{ c->error = STEP_LIMIT; return 0; }}
            if (c->deadline && (c->steps & 63) == 0 && clock_ns() >= (unsigned long long)c->deadline) {{ c->error = DEADLINE; return 0; }}
            int item = edge(c, iter_ref, i, 0);
            current_sum = reduce_add(c, current_sum, item);
            if (c->error || c->h.error) return 0;
        }}
        reducer_push_result(c, caller, current_sum);
        return 1;
    }} else if (itag == T_RANGE_NODE) {{
        long long count = range_size(c, iter_ref);
        if (c->error || c->h.error) return 0;
        long long st = 0, stp = 0;
        if (read_int64(&c->h, edge(c, iter_ref, 0, 0), &st) != 0 ||
            read_int64(&c->h, edge(c, iter_ref, 2, 0), &stp) != 0) {{
            c->error = BAD_CALL; return 0;
        }}
        for (long long i = 0; i < count; i++) {{
            if (++c->steps > c->step_limit) {{ c->error = STEP_LIMIT; return 0; }}
            if (c->deadline && (c->steps & 63) == 0 && clock_ns() >= (unsigned long long)c->deadline) {{ c->error = DEADLINE; return 0; }}
            long long v = (long long)((unsigned long long)st + (unsigned long long)i * (unsigned long long)stp);
            int item = make_int64(&c->h, v);
            if (c->h.error != ERROR_OK) return 0;
            current_sum = reduce_add(c, current_sum, item);
            if (c->error || c->h.error) return 0;
        }}
        reducer_push_result(c, caller, current_sum);
        return 1;
    }} else if (itag == T_ITER) {{
        while (true) {{
            if (++c->steps > c->step_limit) {{ c->error = STEP_LIMIT; return 0; }}
            if (c->deadline && (c->steps & 63) == 0 && clock_ns() >= (unsigned long long)c->deadline) {{ c->error = DEADLINE; return 0; }}
            int item = iterator_next(c, iter_ref);
            if (item == MISSING) break;
            current_sum = reduce_add(c, current_sum, item);
            if (c->error || c->h.error) return 0;
        }}
        if (!c->error && !c->h.error) reducer_push_result(c, caller, current_sum);
        return 1;
    }} else {{
        c->error = UNSUPPORTED_TYPE;
        return 0;
    }}
}}

// Materialized sequence reducer for min() and max()
__device__ inline int reduce_min_max_sequence(Context* c, int iter_ref, int is_max, int has_default, int default_val, int caller) {{
    int itag = kind(c, iter_ref);
    int cmp_mode = is_max ? 4 : 0;
    int best = MISSING;
    int count = 0;
    if (itag == TAG_LIST || itag == TAG_TUPLE || itag == TAG_DICT ||
        (itag >= 8 && itag <= 10) || itag == 21 || itag == 22) {{
        int cnt = length(c, iter_ref);
        for (int i = 0; i < cnt; i++) {{
            if (++c->steps > c->step_limit) {{ c->error = STEP_LIMIT; return 0; }}
            if (c->deadline && (c->steps & 63) == 0 && clock_ns() >= (unsigned long long)c->deadline) {{ c->error = DEADLINE; return 0; }}
            int item = edge(c, iter_ref, i, 0);
            if (count == 0) {{
                best = item;
            }} else {{
                if (compare(c, item, best, cmp_mode)) best = item;
                if (c->error || c->h.error) return 0;
            }}
            count++;
        }}
    }} else if (itag == T_RANGE_NODE) {{
        long long r_cnt = range_size(c, iter_ref);
        if (c->error || c->h.error) return 0;
        long long st = 0, stp = 0;
        if (read_int64(&c->h, edge(c, iter_ref, 0, 0), &st) != 0 ||
            read_int64(&c->h, edge(c, iter_ref, 2, 0), &stp) != 0) {{
            c->error = BAD_CALL; return 0;
        }}
        for (long long i = 0; i < r_cnt; i++) {{
            if (++c->steps > c->step_limit) {{ c->error = STEP_LIMIT; return 0; }}
            if (c->deadline && (c->steps & 63) == 0 && clock_ns() >= (unsigned long long)c->deadline) {{ c->error = DEADLINE; return 0; }}
            long long v = (long long)((unsigned long long)st + (unsigned long long)i * (unsigned long long)stp);
            int item = make_int64(&c->h, v);
            if (c->h.error != ERROR_OK) return 0;
            if (count == 0) {{
                best = item;
            }} else {{
                if (compare(c, item, best, cmp_mode)) best = item;
                if (c->error || c->h.error) return 0;
            }}
            count++;
        }}
    }} else if (itag == T_ITER) {{
        while (true) {{
            if (++c->steps > c->step_limit) {{ c->error = STEP_LIMIT; return 0; }}
            if (c->deadline && (c->steps & 63) == 0 && clock_ns() >= (unsigned long long)c->deadline) {{ c->error = DEADLINE; return 0; }}
            int item = iterator_next(c, iter_ref);
            if (item == MISSING) break;
            if (count == 0) {{
                best = item;
            }} else {{
                if (compare(c, item, best, cmp_mode)) best = item;
                if (c->error || c->h.error) return 0;
            }}
            count++;
        }}
        if (c->error || c->h.error) return 0;
    }} else {{
        c->error = UNSUPPORTED_TYPE;
        return 0;
    }}

    if (count == 0) {{
        if (has_default) {{
            reducer_push_result(c, caller, default_val);
            return 1;
        }} else {{
            c->error = BAD_CALL;
            return 0;
        }}
    }}
    reducer_push_result(c, caller, best);
    return 1;
}}

// API reducer_call: Initiates reducer call on arguments or starts asynchronous generator consumption.
// Returns 1 if callable was recognized, 0 otherwise.
__device__ inline int reducer_call(Context* c, int callable, const int* args, int nargs, int caller, int kw_names = MISSING, const int* kw_values = 0, int nkw = 0) {{
    const int* n = node(c, callable);
    if (!n || n[0] != T_NATIVE) return 0;
    int intrinsic_id = n[3];
    int reducer_code = 0;
    if (NATIVE_ALL >= 0 && intrinsic_id == NATIVE_ALL) reducer_code = REDUCER_ALL;
    else if (NATIVE_ANY >= 0 && intrinsic_id == NATIVE_ANY) reducer_code = REDUCER_ANY;
    else if (NATIVE_SUM >= 0 && intrinsic_id == NATIVE_SUM) reducer_code = REDUCER_SUM;
    else if (NATIVE_MIN >= 0 && intrinsic_id == NATIVE_MIN) reducer_code = REDUCER_MIN;
    else if (NATIVE_MAX >= 0 && intrinsic_id == NATIVE_MAX) reducer_code = REDUCER_MAX;
    else return 0;

    if (nkw > 0 && (kw_names == MISSING || length(c, kw_names) != nkw)) {{
        c->error = BAD_CALL;
        return 1;
    }}

    switch (reducer_code) {{
        case REDUCER_ALL:
        case REDUCER_ANY: {{
            if (nargs != 1 || nkw != 0) {{
                c->error = BAD_CALL;
                return 1;
            }}
            int iterable = args[0];
            int itag = kind(c, iterable);
            if (itag == T_GEN) {{
                const int* gn = node(c, iterable);
                if (!gn || gn[0] != T_GEN) {{ c->error = BAD_CALL; return 1; }}
                int gen_id = gn[3];
                if (gen_id < 0) {{
                    reducer_push_result(c, caller, (reducer_code == REDUCER_ALL) ? TRUE_REF : FALSE_REF);
                    return 1;
                }}
                if (gen_id >= VM_FRAMES) {{ c->error = BAD_PROGRAM; return 1; }}
                int* gf = frame(c, gen_id);
                if (gf[4] != 2) {{ c->error = BAD_CALL; return 1; }}

                int fields[7] = {{reducer_code, caller, iterable, MISSING, 0, 0, MISSING}};
                int acc = make_tuple(&c->h, fields, 7);
                if (acc < 0 || c->h.error) return 1;
                int* acc_n = mutable_node(c, acc);
                if (!acc_n) return 1;
                acc_n[0] = T_REDUCER_ACCUMULATOR;

                resume_generator(c, iterable, caller, 5, acc, MISSING);
                return 1;
            }} else {{
                if (reducer_code == REDUCER_ALL) {{
                    reduce_all_sequence(c, iterable, caller);
                }} else {{
                    reduce_any_sequence(c, iterable, caller);
                }}
                return 1;
            }}
        }}
        case REDUCER_SUM: {{
            if (nargs < 1 || nargs > 2) {{
                c->error = BAD_CALL;
                return 1;
            }}
            int kw_start = MISSING;
            for (int i = 0; i < nkw; i++) {{
                int name = edge(c, kw_names, i, 0);
                if (kind(c, name) != TAG_STR) {{ c->error = BAD_CALL; return 1; }}
                if (reducer_str_equals(c, name, "start", 5)) {{
                    if (kw_start != MISSING) {{ c->error = BAD_CALL; return 1; }}
                    kw_start = kw_values[i];
                }} else {{
                    c->error = BAD_CALL;
                    return 1;
                }}
            }}
            int start_val = MISSING;
            if (nargs == 2) {{
                if (kw_start != MISSING) {{ c->error = BAD_CALL; return 1; }}
                start_val = args[1];
            }} else {{
                if (kw_start != MISSING) {{
                    start_val = kw_start;
                }} else {{
                    start_val = make_int64(&c->h, 0);
                    if (c->h.error != ERROR_OK) return 1;
                }}
            }}
            if(kind(c,start_val)==TAG_STR){{c->error=BAD_CALL;return 1;}}
            int iterable = args[0];
            int itag = kind(c, iterable);
            if (itag == T_GEN) {{
                const int* gn = node(c, iterable);
                if (!gn || gn[0] != T_GEN) {{ c->error = BAD_CALL; return 1; }}
                int gen_id = gn[3];
                if (gen_id < 0) {{
                    reducer_push_result(c, caller, start_val);
                    return 1;
                }}
                if (gen_id >= VM_FRAMES) {{ c->error = BAD_PROGRAM; return 1; }}
                int* gf = frame(c, gen_id);
                if (gf[4] != 2) {{ c->error = BAD_CALL; return 1; }}

                int fields[7] = {{REDUCER_SUM, caller, iterable, start_val, 0, 0, MISSING}};
                int acc = make_tuple(&c->h, fields, 7);
                if (acc < 0 || c->h.error) return 1;
                int* acc_n = mutable_node(c, acc);
                if (!acc_n) return 1;
                acc_n[0] = T_REDUCER_ACCUMULATOR;

                resume_generator(c, iterable, caller, 5, acc, MISSING);
                return 1;
            }} else {{
                reduce_sum_sequence(c, iterable, start_val, caller);
                return 1;
            }}
        }}
        case REDUCER_MIN:
        case REDUCER_MAX: {{
            if (nargs == 0) {{
                c->error = BAD_CALL;
                return 1;
            }}
            int kw_default = MISSING;
            bool has_default = false;
            for (int i = 0; i < nkw; i++) {{
                int name = edge(c, kw_names, i, 0);
                if (kind(c, name) != TAG_STR) {{ c->error = BAD_CALL; return 1; }}
                if (reducer_str_equals(c, name, "key", 3)) {{
                    // Key callback explicitly rejected (never silently ignored)
                    c->error = BAD_CALL;
                    return 1;
                }} else if (reducer_str_equals(c, name, "default", 7)) {{
                    if (has_default) {{ c->error = BAD_CALL; return 1; }}
                    has_default = true;
                    kw_default = kw_values[i];
                }} else {{
                    c->error = BAD_CALL;
                    return 1;
                }}
            }}

            if (nargs > 1) {{
                if (has_default) {{
                    c->error = BAD_CALL;
                    return 1;
                }}
                int is_max = (reducer_code == REDUCER_MAX);
                int cmp_mode = is_max ? 4 : 0;
                int best = args[0];
                for (int i = 1; i < nargs; i++) {{
                    if (++c->steps > c->step_limit) {{ c->error = STEP_LIMIT; return 1; }}
                    if (compare(c, args[i], best, cmp_mode)) best = args[i];
                    if (c->error || c->h.error) return 1;
                }}
                reducer_push_result(c, caller, best);
                return 1;
            }} else {{
                int iterable = args[0];
                int itag = kind(c, iterable);
                if (itag == T_GEN) {{
                    const int* gn = node(c, iterable);
                    if (!gn || gn[0] != T_GEN) {{ c->error = BAD_CALL; return 1; }}
                    int gen_id = gn[3];
                    if (gen_id < 0) {{
                        if (has_default) {{
                            reducer_push_result(c, caller, kw_default);
                            return 1;
                        }} else {{
                            c->error = BAD_CALL;
                            return 1;
                        }}
                    }}
                    if (gen_id >= VM_FRAMES) {{ c->error = BAD_PROGRAM; return 1; }}
                    int* gf = frame(c, gen_id);
                    if (gf[4] != 2) {{ c->error = BAD_CALL; return 1; }}

                    int fields[7] = {{reducer_code, caller, iterable, MISSING, 0, has_default ? 1 : 0, kw_default}};
                    int acc = make_tuple(&c->h, fields, 7);
                    if (acc < 0 || c->h.error) return 1;
                    int* acc_n = mutable_node(c, acc);
                    if (!acc_n) return 1;
                    acc_n[0] = T_REDUCER_ACCUMULATOR;

                    resume_generator(c, iterable, caller, 5, acc, MISSING);
                    return 1;
                }} else {{
                    reduce_min_max_sequence(c, iterable, (reducer_code == REDUCER_MAX), has_default ? 1 : 0, kw_default, caller);
                    return 1;
                }}
            }}
        }}
        default:
            return 0;
    }}
}}

// API reducer_resume: Resumes reducer on generator yield or exhaustion.
// Output pushes to caller only when finished; sets c->current = caller, otherwise resumes generator.
__device__ inline void reducer_resume(Context* c, int generator, int caller, int accumulator, int item, int exhausted) {{
    if (c->error || c->h.error) return;
    const int* an = node(c, accumulator);
    if (!an || an[0] != T_REDUCER_ACCUMULATOR || an[2] < 7) {{
        c->error = BAD_PROGRAM;
        return;
    }}
    int reducer_code = edge(c, accumulator, 0, 0);
    int current_val  = edge(c, accumulator, 3, 0);
    int has_items    = edge(c, accumulator, 4, 0);
    int has_default  = edge(c, accumulator, 5, 0);
    int default_val  = edge(c, accumulator, 6, 0);

    if (!exhausted) {{
        switch (reducer_code) {{
            case REDUCER_ALL: {{
                int truth = truth_value(c, item);
                if (!truth) {{
                    // Short-circuit: false element found.
                    // Generator frame remains suspended (status 2) for later caller reuse.
                    reducer_push_result(c, caller, FALSE_REF);
                    c->current = caller;
                    return;
                }}
                reducer_acc_set(c, accumulator, 4, has_items + 1);
                resume_generator(c, generator, caller, 5, accumulator, MISSING);
                return;
            }}
            case REDUCER_ANY: {{
                int truth = truth_value(c, item);
                if (truth) {{
                    // Short-circuit: true element found.
                    // Generator frame remains suspended (status 2) for later caller reuse.
                    reducer_push_result(c, caller, TRUE_REF);
                    c->current = caller;
                    return;
                }}
                reducer_acc_set(c, accumulator, 4, has_items + 1);
                resume_generator(c, generator, caller, 5, accumulator, MISSING);
                return;
            }}
            case REDUCER_SUM: {{
                int new_sum = reduce_add(c, current_val, item);
                if (c->error || c->h.error) return;
                reducer_acc_set(c, accumulator, 3, new_sum);
                reducer_acc_set(c, accumulator, 4, has_items + 1);
                resume_generator(c, generator, caller, 5, accumulator, MISSING);
                return;
            }}
            case REDUCER_MIN: {{
                if (has_items == 0) {{
                    reducer_acc_set(c, accumulator, 3, item);
                    reducer_acc_set(c, accumulator, 4, 1);
                }} else {{
                    if (compare(c, item, current_val, 0)) {{
                        reducer_acc_set(c, accumulator, 3, item);
                    }}
                    if (c->error || c->h.error) return;
                    reducer_acc_set(c, accumulator, 4, has_items + 1);
                }}
                resume_generator(c, generator, caller, 5, accumulator, MISSING);
                return;
            }}
            case REDUCER_MAX: {{
                if (has_items == 0) {{
                    reducer_acc_set(c, accumulator, 3, item);
                    reducer_acc_set(c, accumulator, 4, 1);
                }} else {{
                    if (compare(c, item, current_val, 4)) {{
                        reducer_acc_set(c, accumulator, 3, item);
                    }}
                    if (c->error || c->h.error) return;
                    reducer_acc_set(c, accumulator, 4, has_items + 1);
                }}
                resume_generator(c, generator, caller, 5, accumulator, MISSING);
                return;
            }}
            default: {{
                c->error = BAD_PROGRAM;
                return;
            }}
        }}
    }} else {{
        // Generator exhausted: frame already released by main return_value
        int result = MISSING;
        switch (reducer_code) {{
            case REDUCER_ALL: {{
                result = TRUE_REF;
                break;
            }}
            case REDUCER_ANY: {{
                result = FALSE_REF;
                break;
            }}
            case REDUCER_SUM: {{
                result = current_val;
                break;
            }}
            case REDUCER_MIN:
            case REDUCER_MAX: {{
                if (has_items == 0) {{
                    if (has_default) {{
                        result = default_val;
                    }} else {{
                        c->error = BAD_CALL;
                        return;
                    }}
                }} else {{
                    result = current_val;
                }}
                break;
            }}
            default: {{
                c->error = BAD_PROGRAM;
                return;
            }}
        }}
        reducer_push_result(c, caller, result);
        c->current = caller;
    }}
}}
"""
