"""CUDA source emitter for native random.Random integer-seeded objects.

Provides:
- SUPPORTED_RANDOM_NAMES: Canonical tuple ('random.Random',) of supported random intrinsics.
- SUPPORTED_RANDOM_METHODS: Canonical tuple of supported random instance methods.
- TAG_RANDOM_INSTANCE (40): Metadata tag for Random instance nodes with aligned bmt_state_t in payload.
- TAG_RANDOM_BOUND_METHOD (41): Metadata tag for bound random method references.
- TAG_RANDOM_CLASS (42): Metadata tag for the fallback Random class callable.
- emit_random_vm_source(intrinsic_names): Returns self-contained CUDA C++ source in namespace
  duel_rule_vm defining random_attribute() and random_call().

Implementation Scope and Explicit Limits:
1. No claim of full GPU rule completeness: This module emits device handlers for the native
   MT19937 random.Random object and its core methods. Full rule parity remains an independent target.
2. Strict integer seeds only: Formal duel rules always provide integer seeds. Zero-argument
   nondeterministic Random() and Random(None) are strictly unsupported and raise explicit errors.
   Boolean seed values are strictly rejected. Integer seeds outside signed int64 range trigger
   explicit errors via numeric_int.
3. Seeding logic parity: Seeds are converted into little-endian uint32 words matching CPython's
   abs(seed) normalization and initialized via bmt_init_by_array().
4. Per-object mutable state: Each Random instance stores its mutable bmt_state_t struct in
   heap.payload at an 8-byte aligned offset (tag 40, n[1]=offset). State is preserved per object;
   methods advance the generator naturally without secret reseeding. VM/workspace forks isolate
   state copies via payload replication.
5. In-place sequence mutation: shuffle() operates in-place directly on heap edges (or via list_set),
   rejecting constant/read-only list writes with ERROR_CONSTANT_WRITE.
6. Exact reference extraction: choice() draws an index via bmt_below() and returns the exact
   element reference without wrapping.
7. Checked arithmetic: randrange() and randint() use unsigned span arithmetic to avoid signed
   overflow; results outside int64 are rejected rather than wrapped.
8. 53-bit float composition: random() produces exact IEEE double values in [0.0, 1.0) using
   CPython's 27-bit and 26-bit raw draws: (a * 67108864.0 + b) * (1.0 / 9007199254740992.0).
9. getstate/setstate: Because preserving full version 3 tuples (625 integers) with Gaussian None
   would consume large graph edge/node capacity, getstate() and setstate() are explicitly
   unsupported and raise UNSUPPORTED_OP.

Importing this module does not import PyTorch or initialize CUDA.
"""

from __future__ import annotations

from typing import Sequence

SUPPORTED_RANDOM_NAMES: tuple[str, ...] = ("random.Random",)

SUPPORTED_RANDOM_METHODS: tuple[str, ...] = (
    "shuffle",
    "choice",
    "getrandbits",
    "randrange",
    "randint",
    "random",
    "seed",
    "getstate",
    "setstate",
)

TAG_RANDOM_INSTANCE: int = 40
TAG_RANDOM_BOUND_METHOD: int = 41
TAG_RANDOM_CLASS: int = 42


def emit_random_vm_source(intrinsic_names: tuple[str, ...] | Sequence[str] = ()) -> str:
    """Return CUDA C++ source for native random.Random in namespace duel_rule_vm.

    Static ID for 'random.Random' is resolved from `intrinsic_names`. Absent ID is assigned
    a distinct negative sentinel (-3001) to prevent duplicate switch collisions.
    The emitted functions (random_attribute, random_call) are designed to be inserted
    inside namespace duel_rule_vm after existing helpers before call().
    """
    names_tuple = tuple(intrinsic_names)
    native_random_id = (
        names_tuple.index("random.Random") if "random.Random" in names_tuple else -3001
    )

    return f"""// --- VM Native random.Random Implementation (generated by vm_random.py) ---

#ifndef T_RANDOM_INSTANCE
const int T_RANDOM_INSTANCE = 40;
#endif
#ifndef T_RANDOM_BOUND_METHOD
const int T_RANDOM_BOUND_METHOD = 41;
#endif
#ifndef T_RANDOM_CLASS
const int T_RANDOM_CLASS = 42;
#endif

// Static intrinsic ID for random.Random
const int NATIVE_RANDOM_RANDOM = {native_random_id};

// Method enumeration codes for Random bound methods (Tag 41, stored in n[3])
enum RandomMethodCode {{
    METHOD_RANDOM_SHUFFLE = 1,
    METHOD_RANDOM_CHOICE = 2,
    METHOD_RANDOM_GETRANDBITS = 3,
    METHOD_RANDOM_RANDRANGE = 4,
    METHOD_RANDOM_RANDINT = 5,
    METHOD_RANDOM_RANDOM = 6,
    METHOD_RANDOM_SEED = 7,
    METHOD_RANDOM_GETSTATE = 8,
    METHOD_RANDOM_SETSTATE = 9
}};

// Encode unsigned 64-bit integer into TAG_INT node (1 to 9 little-endian bytes)
__device__ inline int random_make_uint64(Heap* heap, unsigned long long val) {{
    if ((val & 0x8000000000000000ULL) == 0ULL) {{
        return make_int64(heap, (long long)val);
    }}
    if (heap->counts[2] + 9 > heap->max_payload) {{
        heap->error = ERROR_PAYLOAD_CAPACITY;
        return MISSING;
    }}
    if (heap->counts[0] + 1 > heap->max_nodes) {{
        heap->error = ERROR_NODE_CAPACITY;
        return MISSING;
    }}
    int offset = heap->counts[2];
    for (int i = 0; i < 8; i++) {{
        heap->payload[offset + i] = (unsigned char)((val >> (i * 8)) & 0xFF);
    }}
    heap->payload[offset + 8] = 0x00;
    heap->counts[2] += 9;
    int ref = heap->counts[0]++;
    heap->nodes[ref * 4 + 0] = TAG_INT;
    heap->nodes[ref * 4 + 1] = offset;
    heap->nodes[ref * 4 + 2] = 9;
    heap->nodes[ref * 4 + 3] = 0;
    return ref;
}}

// Construct a new Random instance (Tag 40) seeded with an integer.
// Allocates aligned sizeof(bmt_state_t) bytes in heap.payload, validates capacity
// before mutation, and writes metadata after.
__device__ inline int random_construct_instance(Context* c, int seed_ref, int* out) {{
    if (seed_ref == MISSING) {{
        c->error = BAD_CALL;
        return 0;
    }}
    int stag = kind(c, seed_ref);
    if (stag == TAG_NONE) {{
        // Zero args or None seed is unsupported/nondeterministic in formal rules
        c->error = BAD_CALL;
        return 0;
    }}
    if (stag == TAG_BOOL || stag != TAG_INT) {{
        c->error = UNSUPPORTED_TYPE;
        return 0;
    }}
    long long seed_val = 0;
    if (numeric_int(c, seed_ref, &seed_val) != 0 || c->h.error != ERROR_OK) {{
        c->error = BAD_CALL;
        return 0;
    }}

    int current_payload = c->h.counts[2];
    unsigned long long base=(unsigned long long)c->h.payload;
    int aligned_offset=(int)(((base+(unsigned long long)current_payload+7ULL)&~7ULL)-base);
    long long needed_payload=(long long)aligned_offset+(int)sizeof(bmt_state_t);

    // Validate capacities before mutation
    if (needed_payload > c->h.max_payload) {{
        c->h.error = ERROR_PAYLOAD_CAPACITY;
        return 0;
    }}
    if (c->h.counts[0] + 1 > c->h.max_nodes) {{
        c->h.error = ERROR_NODE_CAPACITY;
        return 0;
    }}

    // Initialize bmt_state_t with CPython exact abs(seed) little-endian uint32 words
    bmt_state_t* st = (bmt_state_t*)(c->h.payload + aligned_offset);
    uint32_t words[2];
    size_t key_len = 0;
    if (seed_val == 0) {{
        words[0] = 0;
        key_len = 1;
    }} else {{
        unsigned long long uval = (seed_val < 0) ? (0ULL - (unsigned long long)seed_val) : (unsigned long long)seed_val;
        words[0] = (uint32_t)(uval & 0xFFFFFFFFULL);
        words[1] = (uint32_t)((uval >> 32) & 0xFFFFFFFFULL);
        key_len = (words[1] != 0) ? 2 : 1;
    }}
    bmt_init_by_array(st, words, key_len);

    // Commit payload count and node metadata after successful mutation
    c->h.counts[2] = (int)needed_payload;
    int ref = c->h.counts[0]++;
    c->h.nodes[ref * 4 + 0] = T_RANDOM_INSTANCE;
    c->h.nodes[ref * 4 + 1] = aligned_offset;
    c->h.nodes[ref * 4 + 2] = (int)sizeof(bmt_state_t);
    c->h.nodes[ref * 4 + 3] = 0;
    *out = ref;
    return 1;
}}

// Attribute lookup on Random instances (Tag 40) and module random.
// Returns bound method node (Tag 41, n[1]=owner, n[3]=method_code).
// Returns MISSING with no error set for unsupported attributes or non-Random owners.
__device__ inline int random_attribute(Context* c, int owner, int name) {{
    if (owner == MISSING || name == MISSING) return MISSING;
    int otag = kind(c, owner);
    if (otag == T_RANDOM_INSTANCE) {{
        if (vm_text_equals(c, name, "shuffle")) {{
            return meta(c, T_RANDOM_BOUND_METHOD, owner, 0, METHOD_RANDOM_SHUFFLE);
        }} else if (vm_text_equals(c, name, "choice")) {{
            return meta(c, T_RANDOM_BOUND_METHOD, owner, 0, METHOD_RANDOM_CHOICE);
        }} else if (vm_text_equals(c, name, "getrandbits")) {{
            return meta(c, T_RANDOM_BOUND_METHOD, owner, 0, METHOD_RANDOM_GETRANDBITS);
        }} else if (vm_text_equals(c, name, "randrange")) {{
            return meta(c, T_RANDOM_BOUND_METHOD, owner, 0, METHOD_RANDOM_RANDRANGE);
        }} else if (vm_text_equals(c, name, "randint")) {{
            return meta(c, T_RANDOM_BOUND_METHOD, owner, 0, METHOD_RANDOM_RANDINT);
        }} else if (vm_text_equals(c, name, "random")) {{
            return meta(c, T_RANDOM_BOUND_METHOD, owner, 0, METHOD_RANDOM_RANDOM);
        }} else if (vm_text_equals(c, name, "seed")) {{
            return meta(c, T_RANDOM_BOUND_METHOD, owner, 0, METHOD_RANDOM_SEED);
        }} else if (vm_text_equals(c, name, "getstate")) {{
            return meta(c, T_RANDOM_BOUND_METHOD, owner, 0, METHOD_RANDOM_GETSTATE);
        }} else if (vm_text_equals(c, name, "setstate")) {{
            return meta(c, T_RANDOM_BOUND_METHOD, owner, 0, METHOD_RANDOM_SETSTATE);
        }}
        return MISSING;
    }}
    return MISSING;
}}

// Call handler for random.Random constructor and its bound methods.
// Returns 1 if handled (successful or with explicit error set), 0 if unhandled.
// Result reference is written to *out.
__device__ inline int random_call(Context* c, int callable, const int* args, int nargs, int* out) {{
    const int* cn = node(c, callable);
    if (!cn) return 0;
    int ctag = cn[0];

    // 1. Constructor call: random.Random(seed)
    if ((ctag == T_NATIVE && cn[3] == NATIVE_RANDOM_RANDOM && NATIVE_RANDOM_RANDOM >= 0)) {{
        if (nargs == 0) {{
            // Zero-arg nondeterministic Random unsupported => explicit error
            c->error = BAD_CALL;
            return 1;
        }}
        if (nargs != 1) {{
            c->error = BAD_CALL;
            return 1;
        }}
        random_construct_instance(c, args[0], out);
        return 1;
    }}

    // 2. Bound method call on Random instance
    if (ctag == T_RANDOM_BOUND_METHOD) {{
        int owner = cn[1];
        int method_code = cn[3];

        // Reject mutation on constant / read-only RNG objects
        if (owner < 0) {{
            c->h.error = ERROR_CONSTANT_WRITE;
            return 1;
        }}
        NodeView onv;
        if (!get_node(&c->h, owner, &onv)) {{
            c->error = BAD_PROGRAM;
            return 1;
        }}
        if (onv.tag != T_RANDOM_INSTANCE) {{
            c->error = UNSUPPORTED_TYPE;
            return 1;
        }}
        if (onv.is_constant) {{
            c->h.error = ERROR_CONSTANT_WRITE;
            return 1;
        }}
        if (onv.offset < 0 || (long long)onv.offset + (int)sizeof(bmt_state_t) > c->h.counts[2]) {{
            c->error = BAD_PROGRAM;
            return 1;
        }}

        if(((unsigned long long)(c->h.payload+onv.offset)&7ULL)!=0ULL){{c->error=BAD_PROGRAM;return 1;}}
        bmt_state_t* rng = (bmt_state_t*)(c->h.payload + onv.offset);

        switch (method_code) {{
            case METHOD_RANDOM_SHUFFLE: {{
                if (nargs != 1) {{
                    c->error = BAD_CALL;
                    return 1;
                }}
                int list_ref = args[0];
                if (list_ref < 0) {{
                    c->h.error = ERROR_CONSTANT_WRITE;
                    return 1;
                }}
                NodeView lnv;
                if (!get_node(&c->h, list_ref, &lnv)) {{
                    c->error = BAD_PROGRAM;
                    return 1;
                }}
                if (lnv.tag != TAG_LIST) {{
                    c->error = UNSUPPORTED_TYPE;
                    return 1;
                }}
                if (lnv.is_constant) {{
                    c->h.error = ERROR_CONSTANT_WRITE;
                    return 1;
                }}
                int n = lnv.count;
                int offset = lnv.offset;
                if (offset < 0 || offset + n > c->h.counts[1]) {{
                    c->error = BAD_PROGRAM;
                    return 1;
                }}
                // In-place Fisher-Yates shuffle directly on raw edge slots
                if (n > 1) {{
                    for (int i = n - 1; i > 0; i--) {{
                        uint64_t j = 0;
                        bmt_status_t st = bmt_below(rng, (uint64_t)(i + 1), &j);
                        if (st != BMT_OK) {{
                            c->error = BAD_CALL;
                            return 1;
                        }}
                        int tmp = c->h.edges[(offset + i) * 2 + 0];
                        c->h.edges[(offset + i) * 2 + 0] = c->h.edges[(offset + (int)j) * 2 + 0];
                        c->h.edges[(offset + (int)j) * 2 + 0] = tmp;
                    }}
                }}
                *out = NIL;
                return 1;
            }}

            case METHOD_RANDOM_CHOICE: {{
                if (nargs != 1) {{
                    c->error = BAD_CALL;
                    return 1;
                }}
                int seq_ref = args[0];
                NodeView snv;
                if (!get_node(&c->h, seq_ref, &snv)) {{
                    c->error = BAD_PROGRAM;
                    return 1;
                }}
                if (snv.tag != TAG_LIST && snv.tag != TAG_TUPLE) {{
                    c->error = UNSUPPORTED_TYPE;
                    return 1;
                }}
                int n = snv.count;
                if (n <= 0) {{
                    c->h.error = ERROR_INDEX_OUT_OF_BOUNDS;
                    return 1;
                }}
                uint64_t idx = 0;
                bmt_status_t st = bmt_below(rng, (uint64_t)n, &idx);
                if (st != BMT_OK) {{
                    c->error = BAD_CALL;
                    return 1;
                }}
                // Selects actual element reference from the sequence
                *out = edge(c, seq_ref, (int)idx, 0);
                return 1;
            }}

            case METHOD_RANDOM_GETRANDBITS: {{
                if (nargs != 1) {{
                    c->error = BAD_CALL;
                    return 1;
                }}
                long long k = 0;
                if (numeric_int(c, args[0], &k) != 0 || c->h.error != ERROR_OK) {{
                    c->error = BAD_CALL;
                    return 1;
                }}
                if (k < 0 || k > 64) {{
                    c->error = BAD_CALL;
                    return 1;
                }}
                uint64_t bits = 0;
                bmt_status_t st = bmt_getbits64(rng, (int)k, &bits);
                if (st != BMT_OK) {{
                    c->error = BAD_CALL;
                    return 1;
                }}
                int ref = random_make_uint64(&c->h, bits);
                if (ref < 0 || c->h.error != ERROR_OK) return 1;
                *out = ref;
                return 1;
            }}

            case METHOD_RANDOM_RANDRANGE: {{
                if (nargs < 1 || nargs > 3) {{
                    c->error = BAD_CALL;
                    return 1;
                }}
                long long start_v = 0, stop_v = 0, step_v = 1;
                if (nargs == 1) {{
                    start_v = 0;
                    if (numeric_int(c, args[0], &stop_v) != 0 || c->h.error != ERROR_OK) {{
                        c->error = BAD_CALL;
                        return 1;
                    }}
                    step_v = 1;
                }} else if (nargs == 2) {{
                    if (numeric_int(c, args[0], &start_v) != 0 ||
                        numeric_int(c, args[1], &stop_v) != 0 ||
                        c->h.error != ERROR_OK) {{
                        c->error = BAD_CALL;
                        return 1;
                    }}
                    step_v = 1;
                }} else {{
                    if (numeric_int(c, args[0], &start_v) != 0 ||
                        numeric_int(c, args[1], &stop_v) != 0 ||
                        numeric_int(c, args[2], &step_v) != 0 ||
                        c->h.error != ERROR_OK) {{
                        c->error = BAD_CALL;
                        return 1;
                    }}
                }}
                if (step_v == 0) {{
                    c->error = BAD_CALL;
                    return 1;
                }}
                unsigned long long span = 0, ustep = 0;
                if (step_v > 0) {{
                    if (start_v >= stop_v) {{
                        c->error = BAD_CALL;
                        return 1;
                    }}
                    span = (unsigned long long)stop_v - (unsigned long long)start_v;
                    ustep = (unsigned long long)step_v;
                }} else {{
                    if (start_v <= stop_v) {{
                        c->error = BAD_CALL;
                        return 1;
                    }}
                    span = (unsigned long long)start_v - (unsigned long long)stop_v;
                    ustep = 0ULL - (unsigned long long)step_v;
                }}
                unsigned long long count = (span - 1ULL) / ustep + 1ULL;
                if (count == 0ULL) {{
                    c->error = BAD_CALL;
                    return 1;
                }}
                if (count > 9223372036854775807ULL) {{
                    c->h.error = ERROR_INT_OVERFLOW;
                    return 1;
                }}
                uint64_t r = 0;
                bmt_status_t st = bmt_below(rng, (uint64_t)count, &r);
                if (st != BMT_OK) {{
                    c->error = BAD_CALL;
                    return 1;
                }}
                long long result = 0;
                if (step_v > 0) {{
                    result = (long long)((unsigned long long)start_v + (unsigned long long)r * ustep);
                }} else {{
                    result = (long long)((unsigned long long)start_v - (unsigned long long)r * ustep);
                }}
                int ref = make_int64(&c->h, result);
                if (ref < 0 || c->h.error != ERROR_OK) return 1;
                *out = ref;
                return 1;
            }}

            case METHOD_RANDOM_RANDINT: {{
                if (nargs != 2) {{
                    c->error = BAD_CALL;
                    return 1;
                }}
                long long a_v = 0, b_v = 0;
                if (numeric_int(c, args[0], &a_v) != 0 ||
                    numeric_int(c, args[1], &b_v) != 0 ||
                    c->h.error != ERROR_OK) {{
                    c->error = BAD_CALL;
                    return 1;
                }}
                if (a_v > b_v) {{
                    c->error = BAD_CALL;
                    return 1;
                }}
                unsigned long long count = (unsigned long long)b_v - (unsigned long long)a_v + 1ULL;
                if (count == 0ULL) {{
                    c->h.error = ERROR_INT_OVERFLOW;
                    return 1;
                }}
                uint64_t r = 0;
                bmt_status_t st = bmt_below(rng, (uint64_t)count, &r);
                if (st != BMT_OK) {{
                    c->error = BAD_CALL;
                    return 1;
                }}
                long long result = (long long)((unsigned long long)a_v + (unsigned long long)r);
                int ref = make_int64(&c->h, result);
                if (ref < 0 || c->h.error != ERROR_OK) return 1;
                *out = ref;
                return 1;
            }}

            case METHOD_RANDOM_RANDOM: {{
                if (nargs != 0) {{
                    c->error = BAD_CALL;
                    return 1;
                }}
                // 53-bit CPython float composition
                uint32_t a = bmt_raw_u32(rng) >> 5;
                uint32_t b = bmt_raw_u32(rng) >> 6;
                double val = (a * 67108864.0 + b) * (1.0 / 9007199254740992.0);
                int ref = make_float64(&c->h, val);
                if (ref < 0 || c->h.error != ERROR_OK) return 1;
                *out = ref;
                return 1;
            }}

            case METHOD_RANDOM_SEED: {{
                if (nargs != 1) {{
                    c->error = BAD_CALL;
                    return 1;
                }}
                if (kind(c, args[0]) == TAG_NONE ||
                    kind(c, args[0]) == TAG_BOOL ||
                    kind(c, args[0]) != TAG_INT) {{
                    c->error = UNSUPPORTED_TYPE;
                    return 1;
                }}
                long long s_val = 0;
                if (numeric_int(c, args[0], &s_val) != 0 || c->h.error != ERROR_OK) {{
                    c->error = BAD_CALL;
                    return 1;
                }}
                uint32_t words[2];
                size_t key_len = 0;
                if (s_val == 0) {{
                    words[0] = 0;
                    key_len = 1;
                }} else {{
                    unsigned long long uval = (s_val < 0) ? (0ULL - (unsigned long long)s_val) : (unsigned long long)s_val;
                    words[0] = (uint32_t)(uval & 0xFFFFFFFFULL);
                    words[1] = (uint32_t)((uval >> 32) & 0xFFFFFFFFULL);
                    key_len = (words[1] != 0) ? 2 : 1;
                }}
                bmt_init_by_array(rng, words, key_len);
                *out = NIL;
                return 1;
            }}

            case METHOD_RANDOM_GETSTATE:
            case METHOD_RANDOM_SETSTATE: {{
                // Preserving full 625-integer version 3 tuple and Gaussian None is omitted
                // to maintain bounded graph capacity; explicitly unsupported as permitted.
                c->error = UNSUPPORTED_OP;
                return 1;
            }}

            default:
                c->error = BAD_CALL;
                return 1;
        }}
    }}

    return 0;
}}
"""
